/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.82
 * Generated at: 2018-06-11 02:13:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.home;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.movemini.layers.controller.agenda.Agenda;
import com.movemini.data.OneRecordFactory;
import org.apache.tomcat.util.codec.binary.Base64;
import java.sql.*;
import java.io.*;
import java.util.List;
import java.util.ArrayList;
import com.movemini.config.HardCodeConstants;
import com.movemini.layers.session.SessionBean;
import com.movemini.layers.view.menu.RecordCounter;
import com.movemini.data.DataArray;
import com.movemini.data.Record;
import com.movemini.data.ConnectionWrapper;
import java.sql.DriverManager;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import java.sql.ResultSet;
import java.sql.Statement;

public final class agenda_005ftecnico_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/home/commonSideBarMenu.jsp", Long.valueOf(1527701485317L));
    _jspx_dependants.put("/home/agenda_js.jsp", Long.valueOf(1527701476571L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


	response.setHeader("Cache-Control","no-cache"); //HTTP 1.1
	response.setHeader("Pragma","no-cache"); //HTTP 1.0
	response.setDateHeader ("Expires", 0); //prevents caching at the proxy server

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

try
{
	boolean access = true;


 	String id_evento_status = (String) session.getAttribute("v");
 	String usuarioConsultaCode = (String) session.getAttribute("u");




 	session.setAttribute("id_evento_status", id_evento_status);

 	Record eventoStatusRecord = OneRecordFactory.getFirstRecord("SELECT * FROM cat_evento_status WHERE id_evento_status = " + id_evento_status);


    if(access
//     		session.getAttribute("ID_USER") != null
    		) {





      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n");
      out.write("    <!-- Meta, title, CSS, favicons, etc. -->\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("\n");
      out.write("    <title>SAO - Eventos</title>\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/base/jquery-ui.css\">\n");
      out.write("    <!-- Bootstrap -->\n");
      out.write("    <link href=\"../home/vendors/bootstrap/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <!-- Font Awesome -->\n");
      out.write("    <link href=\"../home/vendors/font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\">\n");
      out.write("    <!-- NProgress -->\n");
      out.write("    <link href=\"../home/vendors/nprogress/nprogress.css\" rel=\"stylesheet\">\n");
      out.write("    <!-- iCheck -->\n");
      out.write("    <link href=\"../home/vendors/iCheck/skins/flat/green.css\" rel=\"stylesheet\">\n");
      out.write("    <!-- Datatables -->\n");
      out.write("    <link href=\"../home/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"../home/vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"../home/vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"../home/vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"../home/vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"../home/css/datepicker.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- FullCalendar -->\n");
      out.write("    <link href=\"vendors/fullcalendar/dist/fullcalendar.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"vendors/fullcalendar/dist/fullcalendar.print.css\" rel=\"stylesheet\" media=\"print\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    <!-- Custom Theme Style -->\n");
      out.write("    <link href=\"../home/build/css/custom.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("    <style type=\"text/css\">\n");
      out.write("\n");
      out.write("    .ui-datepicker-calendar {\n");
      out.write("    display: none;\n");
      out.write("    }\n");
      out.write("\t\t.fc-time{ display: none; }\n");
      out.write("    </style>\n");
      out.write("  </head>\n");
      out.write("  <body class=\"nav-md\">\n");
      out.write("    <div class=\"container body\">\n");
      out.write("      <div class=\"main_container\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("      \t");
      out.write('\n');
      out.write('\n');

	response.setHeader("Cache-Control","no-cache"); //HTTP 1.1
	response.setHeader("Pragma","no-cache"); //HTTP 1.0
	response.setDateHeader ("Expires", 0); //prevents caching at the proxy server

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");




// 	Connection connx = ConnectionWrapper.getDirectJDBCConnection();



Record user = SessionBean.getInstance(request).getUser();



// 	List<String> lstMenuPadres = new ArrayList<String>();
// 	String Role = "";

// 	Statement stScreen = connx.createStatement();
// 	ResultSet rsScreen = stScreen.executeQuery("SELECT * FROM screen_role WHERE ID_ROLE = '"+session.getAttribute("ID_ROLE")+"'");
// 	while(rsScreen.next()){
// 		Statement stName = connx.createStatement();
// 		ResultSet rsName = stName.executeQuery("SELECT * FROM menu WHERE ID_SCREEN = '"+rsScreen.getInt(1)+"' and ID_PADRE = 0 AND ID_ROLE ="+session.getAttribute("ID_ROLE")+" ORDER BY ID_ORDER, ID");
// 		while(rsName.next()){
// 			lstMenuPadres.add(rsName.getString("NAME"));
// 		}
// 	}



	ArrayList<Record> menuParents = DataArray.getArrayList("SELECT * FROM ss_menu WHERE id_menu_padre = 0 AND accesos LIKE '%" + user.get("id_rol") + "%' ORDER BY id_orden");




// 	Statement stR = connx.createStatement();
// 	ResultSet rsR = stR.executeQuery("SELECT * FROM role WHERE ID = "+session.getAttribute("ID_ROLE")+"");
// 	while(rsR.next()){
// 		Role = rsR.getString(2);
// 	}




// 	String[] dtaUser = new String[10];
// 	String imagen = "";
// 	String imagenUser = "";
// 	Statement stUs = connx.createStatement();
// 	//ResultSet rsUs = stUs.executeQuery("SELECT * FROM user WHERE ID = "+session.getAttribute("ID_USER")+"");
// 	while(rsUs.next()){
// // 		dtaUser[0] = rsUs.getString(1);
// // 		dtaUser[1] = rsUs.getString(2);
// // 		dtaUser[2] = rsUs.getString(3);
// // 		dtaUser[3] = rsUs.getString(4);
// // 		dtaUser[4] = rsUs.getString(5);
// // 		dtaUser[5] = rsUs.getString(6);
// // 		dtaUser[6] = rsUs.getString(7);
// // 		dtaUser[7] = rsUs.getString(8);
// 		if(rsUs.getString(9)!= null){
// 			imagen = rsUs.getString(9);
// 		}
// 		else{
// 			Statement stDef = connx.createStatement();
// 			ResultSet rsDef = stDef.executeQuery("SELECT * FROM configuracion WHERE id_conf = 3");
// 			while(rsDef.next()){
// 				imagen = rsDef.getString(3);
// 			}
// 		}
// 		dtaUser[9] = rsUs.getString(10);
// 	}




// 	Statement stEditEvento = connx.createStatement();
// 	ResultSet rsEditEvento = stEditEvento.executeQuery("SELECT * FROM evento WHERE ID = "+request.getParameter("ID_EVENTO")+"");
// 	String[] lstEvento = new String[12];
// 	while(rsEditEvento.next()){
// 		lstEvento[0] =  rsEditEvento.getString(1);
// 		lstEvento[1] =  rsEditEvento.getString(2);
// 		lstEvento[2] =  rsEditEvento.getString(3);
// 		lstEvento[3] =  rsEditEvento.getString(4);
// 		lstEvento[4] =  rsEditEvento.getString(5);
// 		lstEvento[5] =  rsEditEvento.getString(6);
// 		lstEvento[6] =  rsEditEvento.getString(7);
// 	}










      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("      <div class=\"col-md-3 left_col\">\n");
      out.write("          <div class=\"left_col scroll-view\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t \t\t<div class=\"navbar nav_title\" style=\"border: 0;\">\n");
      out.write("\t\t              <a href=\"main.jsp\" class=\"site_title\"> <span>SAO</span></a>\n");
      out.write("\t\t            </div>\n");
      out.write("\t\t            <div class=\"clearfix\"></div>\n");
      out.write("\n");
      out.write("\t\t           <!--\n");
      out.write("\t\t            -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t            <!-- menu profile quick info -->\n");
      out.write("\t\t            <div class=\"profile\">\n");
      out.write("\t\t              <div class=\"profile_pic\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t              <img id='profileImg1' src=\"/");
      out.print( HardCodeConstants.CONTEXT_PATH );
      out.write("/ProfilePhotoServlet\" width=\"40%\" height=\"40%\" class=\"img-circle profile_img\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t              </div>\n");
      out.write("\t\t              <div class=\"profile_info\">\n");
      out.write("\t\t                <!--<span>");
      out.print( user.get("rol_name") );
      out.write("</span>-->\n");
      out.write("\t\t                <h2>");
      out.print( user.get("nombre") );
      out.print(" ");
      out.print( user.get("apellido") );
      out.write("</h2>\n");
      out.write("\t\t              </div>\n");
      out.write("\t\t            </div>\n");
      out.write("\t\t            <!-- /menu profile quick info -->\n");
      out.write("\n");
      out.write("\t\t            <br />\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t<!-- sidebar menu -->\n");
      out.write("\t\t            <div id=\"sidebar-menu\" class=\"main_menu_side hidden-print main_menu\">\n");
      out.write("\t\t              <div class=\"menu_section\">\n");
      out.write("\t\t                <!-- <h3>Menu</h3>-->\n");
      out.write("\t\t                <br>\n");
      out.write("\t\t                <br>\n");
      out.write("\t\t                <br>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t                <ul class=\"nav side-menu\">\n");
      out.write("\t\t                ");




		                for (Record recordParent: menuParents) {

		                	//Statement st1 = connx.createStatement();
		                    //ResultSet rs1 = st1.executeQuery("SELECT * FROM menu m WHERE m.NAME = '"+item+"' AND ID_ROLE = "+session.getAttribute("ID_ROLE")+" ORDER BY ID_ORDER, ID");

		                    
      out.write("\n");
      out.write("\t\t                \t<li><a>\n");
      out.write("\t\t                \t\t\t<i class=\"");
      out.print(recordParent.getString("class") );
      out.write("\"></i>\n");
      out.write("\t\t                \t\t\t\t\t");
      out.print(recordParent.get("nombre") );
      out.write("\n");
      out.write("\t\t                \t\t\t\t\t<span class=\"fa fa-chevron-down\"></span>\n");
      out.write("\t\t                \t\t</a>\n");
      out.write("\t\t                \t\t<ul class=\"nav child_menu\">\n");
      out.write("\t\t                \t\t");





		                	ArrayList<Record> menuChilds = DataArray.getArrayList("SELECT * FROM ss_menu WHERE id_menu_padre = " + recordParent.get("id_menu") + " AND accesos LIKE '%" + user.get("id_rol") + "%' ORDER BY id_orden");

		                	for (Record recordChild: menuChilds) {
		                    	
      out.write("\n");
      out.write("\n");
      out.write("\t\t                \t\t\t<li class=\"");
      out.print(recordChild.getString("class") );
      out.write("\"><a href=\"");
      out.print(recordChild.getString("url"));
      out.write("\">\n");
      out.write("\t\t                \t\t\t");
      out.print( recordChild.getString("nombre") );
      out.write("\n");
      out.write("\t\t                \t\t\t");
      out.print( RecordCounter.getCount(user.get("id_usuario"), recordChild.get("url")) );
      out.write("\n");
      out.write("\t\t                \t\t\t</a></li>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t                \t\t\t");

		                    }

		                    
      out.write("\n");
      out.write("\t\t                    \t</ul>\n");
      out.write("\t\t                   \t</li>\n");
      out.write("\t\t                    ");

		                }
		                
      out.write("\n");
      out.write("\t\t                </ul>\n");
      out.write("\t\t              </div>\n");
      out.write("\t\t            </div>\n");
      out.write("\t\t            <!-- /sidebar menu -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t            <!-- /menu footer buttons -->\n");
      out.write("\t\t            <div class=\"sidebar-footer hidden-small\">\n");
      out.write("\t\t            <!--\n");
      out.write("\t\t              <a data-toggle=\"tooltip\" data-placement=\"top\" title=\"Settings\">\n");
      out.write("\t\t                <span class=\"glyphicon glyphicon-cog\" aria-hidden=\"true\"></span>\n");
      out.write("\t\t              </a>\n");
      out.write("\t\t              <a data-toggle=\"tooltip\" data-placement=\"top\" title=\"FullScreen\">\n");
      out.write("\t\t                <span class=\"glyphicon glyphicon-fullscreen\" aria-hidden=\"true\"></span>\n");
      out.write("\t\t              </a>\n");
      out.write("\t\t              <a data-toggle=\"tooltip\" data-placement=\"top\" title=\"Lock\">\n");
      out.write("\t\t                <span class=\"glyphicon glyphicon-eye-close\" aria-hidden=\"true\"></span>\n");
      out.write("\t\t              </a>\n");
      out.write("\t\t               -->\n");
      out.write("\t\t              <a data-toggle=\"tooltip\" data-placement=\"top\" title=\"Logout\" href=\"../home/logOut.jsp\">\n");
      out.write("\t\t                <span class=\"glyphicon glyphicon-off\" aria-hidden=\"true\"></span>\n");
      out.write("\t\t              </a>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<!--\t<a href=\"javascript:void(0);\" data-toggle=\"tooltip\" onclick=\"alert()\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"glyphicon glyphicon-bell\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"badge bg-green\">6</span>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t</a> -->\n");
      out.write("\n");
      out.write("\t\t            </div>\n");
      out.write("\t\t            <!-- /menu footer buttons -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("        <!-- top navigation -->\n");
      out.write("        <div class=\"top_nav\">\n");
      out.write("          <div class=\"nav_menu\">\n");
      out.write("            <nav>\n");
      out.write("              <div class=\"nav toggle\">\n");
      out.write("                <a id=\"menu_toggle\"><i class=\"fa fa-bars\"></i></a>\n");
      out.write("              </div>\n");
      out.write("\n");
      out.write("              <ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("                <li class=\"\">\n");
      out.write("                  <a href=\"javascript:;\" class=\"user-profile dropdown-toggle\" data-toggle=\"dropdown\" aria-expanded=\"false\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                    <img id='profileImg2' src=\"/");
      out.print( HardCodeConstants.CONTEXT_PATH );
      out.write("/ProfilePhotoServlet\" width=\"40%\" height=\"40%\">\n");
      out.write("\n");
      out.write("                    ");
      out.print( user.get("nombre") );
      out.print(" ");
      out.print( user.get("apellido") );
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                    <span class=\" fa fa-angle-down\"></span>\n");
      out.write("                  </a>\n");
      out.write("                  <ul class=\"dropdown-menu dropdown-usermenu pull-right\">\n");
      out.write("                    <li><a href=\"../home/logOut.jsp\"><i class=\"fa fa-sign-out pull-right\"></i>Salir </a></li>\n");
      out.write("\n");
      out.write("                  </ul>\n");
      out.write("                </li>\n");
      out.write("\n");
      out.write("              </ul>\n");
      out.write("            </nav>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- /top navigation -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");



// ConnectionWrapper.closeAll(rsScreen, stScreen, rsR, stR, connx);



      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("         <div class=\"right_col\" role=\"main\">\n");
      out.write("          <div class=\"\">\n");
      out.write("            <div class=\"page-title\">\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"clearfix\"></div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"col-md-12 col-sm-12 col-xs-12\">\n");
      out.write("                <div class=\"x_panel\">\n");
      out.write("                  <div class=\"x_title\">\n");
      out.write("                    <p><strong>AGENDA T&Eacute;CNICO</strong> </p>\n");
      out.write("                    <ul class=\"nav navbar-right panel_toolbox\">\n");
      out.write("                    </ul>\n");
      out.write("                    <div class=\"clearfix\"></div>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"x_content\">\n");
      out.write("                    <p class=\"text-muted font-13 m-b-30\">\n");
      out.write("                    </p>\n");
      out.write("\n");
      out.write("                    <div align=\"right\">\n");
      out.write("                  \t<div class=\"row\">\n");
      out.write("                  \t\t<div class=\"col-md-3\">\n");
      out.write("\t                  \t\t<div class=\"row\">\n");
      out.write("\t                  \t\t\t<div class=\"col-md-2\">\n");
      out.write("\t                  \t\t\t\t<label>Cliente:</label>\n");
      out.write("\t                  \t\t\t</div>\n");
      out.write("\t                  \t\t\t<div class=\"col-md-9\">\n");
      out.write("\t                  \t\t\t\t<div id=\"divComboCliente\"></div>\n");
      out.write("\t                  \t\t\t</div>\n");
      out.write("\t                  \t\t</div>\n");
      out.write("\t                  \t</div>\n");
      out.write("\t                  \t<div class=\"col-md-3\">\n");
      out.write("\t                  \t\t<div class=\"row\">\n");
      out.write("\t                  \t\t\t<div class=\"col-md-2\">\n");
      out.write("\t                  \t\t\t\t<label>Evento:</label>\n");
      out.write("\t                  \t\t\t</div>\n");
      out.write("\t                  \t\t\t<div class=\"col-md-9\">\n");
      out.write("\t                  \t\t\t\t<div id=\"divComboNombreEvento\"></div>\n");
      out.write("\t                  \t\t\t</div>\n");
      out.write("\t                  \t\t</div>\n");
      out.write("\t                  \t</div>\n");
      out.write("\t                  \t<div class=\"col-md-3\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-2\">\n");
      out.write("\t                  \t\t\t\t<label>Estatus:</label>\n");
      out.write("\t                  \t\t\t</div>\n");
      out.write("\t                  \t\t\t<div class=\"col-md-9\">\n");
      out.write("\t                  \t\t\t\t<div id=\"divComboEstatus\" class=\"col\"></div>\n");
      out.write("\t                  \t\t\t</div>\n");
      out.write("\t                  \t\t</div>\n");
      out.write("\t                  \t</div>\n");
      out.write("\t                  \t<div class=\"col-sm-2\">\n");
      out.write("\t                  \t\t<div class=\"row\"  style=\"display: none\">\n");
      out.write("\t                  \t\t\t<div class=\"col-md-3\">\n");
      out.write("\t                  \t\t\t\t<label for=\"startDate\">Fecha:</label>\n");
      out.write("\t                  \t\t\t</div>\n");
      out.write("\t                  \t\t\t<div class=\"col-md-9\">\n");
      out.write("\t    \t\t\t\t \t\t\t<input name=\"startDate\" id=\"startDate\" class=\"date-picker\" />\n");
      out.write("\t    \t\t\t\t \t\t</div>\n");
      out.write("\t    \t\t\t\t\t</div>\n");
      out.write("\t                  \t</div>\n");
      out.write("\n");
      out.write("\t                  \t<div class=\"col-sm-1\">\n");
      out.write("\t                  \t\t<input type=\"button\" value=\"Buscar\" onclick=\"funcObtenerAgendaTecnicos();\">\n");
      out.write("\t                  \t</div>\n");
      out.write("                    </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<div id='calendar'></div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    <!-- calendar modal -->\n");
      out.write("    <div id=\"CalenderModalNew\" class=\"modal fade\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\n");
      out.write("      <div class=\"modal-dialog\">\n");
      out.write("        <div class=\"modal-content\">\n");
      out.write("\n");
      out.write("          <div class=\"modal-header\">\n");
      out.write("            <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">ï¿½</button>\n");
      out.write("            <h4 class=\"modal-title\" id=\"myModalLabel\">New Calendar Entry</h4>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"modal-body\">\n");
      out.write("            <div id=\"testmodal\" style=\"padding: 5px 20px;\">\n");
      out.write("              <form id=\"antoform\" class=\"form-horizontal calender\" role=\"form\">\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                  <label class=\"col-sm-3 control-label\">Title</label>\n");
      out.write("                  <div class=\"col-sm-9\">\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"title\" name=\"title\">\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                  <label class=\"col-sm-3 control-label\">Description</label>\n");
      out.write("                  <div class=\"col-sm-9\">\n");
      out.write("                    <textarea class=\"form-control\" style=\"height:55px;\" id=\"descr\" name=\"descr\"></textarea>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              </form>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"modal-footer\">\n");
      out.write("            <button type=\"button\" class=\"btn btn-default antoclose\" data-dismiss=\"modal\">Close</button>\n");
      out.write("            <button type=\"button\" class=\"btn btn-primary antosubmit\">Save changes</button>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    <div id=\"CalenderModalEdit\" class=\"modal fade\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\n");
      out.write("      <div class=\"modal-dialog\">\n");
      out.write("        <div class=\"modal-content\">\n");
      out.write("\n");
      out.write("          <div class=\"modal-header\">\n");
      out.write("            <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">X</button>\n");
      out.write("            <h4 class=\"modal-title\" id=\"myModalLabel2\">Detalle del Evento</h4>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"modal-body\">\n");
      out.write("\n");
      out.write("            <div id=\"testmodal2\" style=\"padding: 5px 20px;\">\n");
      out.write("              <form id=\"antoform2\" class=\"form-horizontal calender\" role=\"form\">\n");
      out.write("\t\t\t\t\t\t\t<div id=\"nFormAgenda1\">\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                  <label class=\"col-sm-3 control-label\">Evento</label>\n");
      out.write("                  <div class=\"col-sm-9\">\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"title2\" name=\"title2\" disabled=\"disabled\">\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                  <label class=\"col-sm-3 control-label\">Cliente</label>\n");
      out.write("                  <div class=\"col-sm-9\">\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"cliente\" name=\"cliente\" disabled=\"disabled\">\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                  <label class=\"col-sm-3 control-label\">Fecha</label>\n");
      out.write("                  <div class=\"col-sm-9\">\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"fecha\" name=\"fecha\" disabled=\"disabled\">\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("<!--                 <div class=\"form-group\"> -->\n");
      out.write("<!--                   <label class=\"col-sm-3 control-label\">Sala</label> -->\n");
      out.write("<!--                   <div class=\"col-sm-9\"> -->\n");
      out.write("<!--                     <input type=\"text\" class=\"form-control\" id=\"sala\" name=\"sala\" disabled=\"disabled\"> -->\n");
      out.write("<!--                   </div> -->\n");
      out.write("<!--                 </div> -->\n");
      out.write("<!--                 <div class=\"form-group\"> -->\n");
      out.write("<!--                   <label class=\"col-sm-3 control-label\">Interprete</label> -->\n");
      out.write("<!--                   <div class=\"col-sm-9\"> -->\n");
      out.write("<!--                     <input type=\"text\" class=\"form-control\" id=\"interprete\" name=\"interprete\" disabled=\"disabled\"> -->\n");
      out.write("<!--                   </div> -->\n");
      out.write("<!--                 </div> -->\n");
      out.write("\n");
      out.write("\n");
      out.write("<!--                 <div class=\"form-group\"> -->\n");
      out.write("<!--                   <label class=\"col-sm-3 control-label\">Title</label> -->\n");
      out.write("<!--                   <div class=\"col-sm-9\"> -->\n");
      out.write("<!--                     <input type=\"text\" class=\"form-control\" id=\"title2\" name=\"title2\"> -->\n");
      out.write("<!--                   </div> -->\n");
      out.write("<!--                 </div> -->\n");
      out.write("<!--                 <div class=\"form-group\"> -->\n");
      out.write("<!--                   <label class=\"col-sm-3 control-label\">Description</label> -->\n");
      out.write("<!--                   <div class=\"col-sm-9\"> -->\n");
      out.write("<!--                     <textarea class=\"form-control\" style=\"height:55px;\" id=\"descr2\" name=\"descr\"></textarea> -->\n");
      out.write("<!--                   </div> -->\n");
      out.write("<!--                 </div> -->\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"nFormAgenda2\"></div>\n");
      out.write("              </form>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"modal-footer\">\n");
      out.write("\n");
      out.write("\n");
      out.write("          \t<form action=\"adm_evento_sedes.jsp\" id=\"formXYZ\">\n");
      out.write("\n");
      out.write("          \t<input type=\"hidden\" id=\"ID_EVENTO\" name=\"ID_EVENTO\">\n");
      out.write("          \t<button type=\"button\" class=\"btn btn-default\" id=\"btnMemoEvento\"   onclick=\"formXYZ.action='reporte_memo_servicio_pdf.jsp';formXYZ.submit()\">Ver Memo de Servicio</button>\n");
      out.write("          \t</form>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("            <button type=\"button\" class=\"btn btn-default antoclose2\" data-dismiss=\"modal\">Cerrar</button>\n");
      out.write("<!--             <button type=\"button\" class=\"btn btn-primary antosubmit2\">Save changes</button> -->\n");
      out.write("\n");
      out.write("\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    <div id=\"fc_create\" data-toggle=\"modal\" data-target=\"#CalenderModalNew\"></div>\n");
      out.write("    <div id=\"fc_edit\" data-toggle=\"modal\" data-target=\"#CalenderModalEdit\"></div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("               <script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("               </script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("     </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("               <footer>\n");
      out.write("          <div class=\"pull-right\">\n");
      out.write("\n");
      out.write("          </div>\n");
      out.write("          <div class=\"clearfix\"></div>\n");
      out.write("        </footer>\n");
      out.write("        <!-- /footer content -->\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    ");

	response.setHeader("Cache-Control","no-cache"); //HTTP 1.1
	response.setHeader("Pragma","no-cache"); //HTTP 1.0
	response.setDateHeader ("Expires", 0); //prevents caching at the proxy server

      out.write("\r\n");
      out.write("\r\n");

	// OK

      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("var funcObternerEstatusEvento = function (){\r\n");
      out.write("\r\n");
      out.write("\t$.ajax({\r\n");
      out.write(" \t\ttype:'POST',\r\n");
      out.write(" \t\turl :\"/SAO/EventoSelectEstatusServlet\",\r\n");
      out.write(" \t\t//data: {\r\n");
      out.write(" \t\t//},\r\n");
      out.write(" \t\tsuccess: function(data) {\r\n");
      out.write("\r\n");
      out.write(" \t\t\t$(\"#divComboEstatus\").empty();\r\n");
      out.write(" \t\t\t$(\"#divComboEstatus\").append(data);\r\n");
      out.write("\r\n");
      out.write(" \t\t},\r\n");
      out.write(" \t\terror:function(exception){console.log('Exeption:'+exception); /*logSystem*/ swal(  'Error',  'Proceso no completado',  'error');}\r\n");
      out.write(" \t});\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("var funcObternerComboEventoNombre = function (){\r\n");
      out.write("\r\n");
      out.write("\t$.ajax({\r\n");
      out.write(" \t\ttype:'POST',\r\n");
      out.write(" \t\turl :\"/SAO/EventoSelectComboNombreServlet\",\r\n");
      out.write(" \t\t//data: {\r\n");
      out.write(" \t\t//},\r\n");
      out.write(" \t\tsuccess: function(data) {\r\n");
      out.write("\r\n");
      out.write(" \t\t\t$(\"#divComboNombreEvento\").empty();\r\n");
      out.write(" \t\t\t$(\"#divComboNombreEvento\").append(data);\r\n");
      out.write("\r\n");
      out.write(" \t\t},\r\n");
      out.write(" \t\terror:function(exception){console.log('Exeption:'+exception); /*logSystem*/ swal(  'Error',  'Proceso no completado',  'error');}\r\n");
      out.write(" \t});\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("//\r\n");
      out.write("var funcObternerComboCliente = function (){\r\n");
      out.write("\r\n");
      out.write("\t$.ajax({\r\n");
      out.write(" \t\ttype:'POST',\r\n");
      out.write(" \t\turl :\"/SAO/EventoSelectComboClienteServlet\",\r\n");
      out.write(" \t\t//data: {\r\n");
      out.write(" \t\t//},\r\n");
      out.write(" \t\tsuccess: function(data) {\r\n");
      out.write("\r\n");
      out.write(" \t\t\t$(\"#divComboCliente\").empty();\r\n");
      out.write(" \t\t\t$(\"#divComboCliente\").append(data);\r\n");
      out.write("\r\n");
      out.write(" \t\t},\r\n");
      out.write(" \t\terror:function(exception){console.log('Exeption:'+exception); /*logSystem*/ swal(  'Error',  'Proceso no completado',  'error');}\r\n");
      out.write(" \t});\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("var funcObtenerAgenda = function (){\r\n");
      out.write("\r\n");
      out.write("\tvar idCliente =  $(\"#id_cliente option:selected\").val();\r\n");
      out.write("\tvar idEvento =  $(\"#id_evento option:selected\").val();\r\n");
      out.write("\tvar idEstatusEvento =  $(\"#id_evento_status option:selected\").val();\r\n");
      out.write("\tvar fechaSeleccionada = $(\"#startDate\").val();\r\n");
      out.write("\r\n");
      out.write("\tif(fechaSeleccionada.length > 0){\r\n");
      out.write("\t\tfechaSeleccionada = fechaSeleccionada.split('-')[1];\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t$.ajax({\r\n");
      out.write(" \t\ttype:'POST',\r\n");
      out.write(" \t\turl :\"/SAO/AgendaSelectServlet\",\r\n");
      out.write(" \t\tdata: {\r\n");
      out.write(" \t\t\tid_cliente : idCliente,\r\n");
      out.write(" \t\t\tid_evento : idEvento,\r\n");
      out.write(" \t\t\tid_estatus : idEstatusEvento,\r\n");
      out.write(" \t\t\tfecha : fechaSeleccionada\r\n");
      out.write(" \t\t},\r\n");
      out.write(" \t\tsuccess: function(data) {\r\n");
      out.write(" \tdebugger;\r\n");
      out.write("\t\t\tvar argEventos = eval(data);\r\n");
      out.write("\r\n");
      out.write(" \t\t\t$('#calendar').fullCalendar( 'removeEvents');\r\n");
      out.write(" \t\t    $('#calendar').fullCalendar('addEventSource', argEventos);\r\n");
      out.write("\r\n");
      out.write(" \t\t   if( $(\"#startDate\").val().length > 0){\r\n");
      out.write(" \t\t   \t$('#calendar').fullCalendar('gotoDate', new Date($(\"#startDate\").val().split('-')[1], $(\"#startDate\").val().split('-')[0], 1));\r\n");
      out.write(" \t\t   }\r\n");
      out.write("\r\n");
      out.write(" \t\t},\r\n");
      out.write(" \t\terror:function(exception){console.log('Exeption:'+exception); /*logSystem*/ swal(  'Error',  'Proceso no completado',  'error');}\r\n");
      out.write(" \t});\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("var funcObtenerAgendaInterpretes = function (){\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\tvar idCliente =  $(\"#id_cliente option:selected\").val();\r\n");
      out.write("\tvar idEvento =  $(\"#id_evento option:selected\").val();\r\n");
      out.write("\tvar idEstatusEvento =  $(\"#id_evento_status option:selected\").val();\r\n");
      out.write("\tvar fechaSeleccionada = $(\"#startDate\").val();\r\n");
      out.write("\r\n");
      out.write("\tif(fechaSeleccionada.length > 0){\r\n");
      out.write("\t\tfechaSeleccionada = fechaSeleccionada.split('-')[1];\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t$.ajax({\r\n");
      out.write(" \t\ttype:'POST',\r\n");
      out.write(" \t\turl :\"/SAO/AgendaSelectInterpreteServlet\",\r\n");
      out.write(" \t\tdata: {\r\n");
      out.write(" \t\t\tid_cliente : idCliente,\r\n");
      out.write(" \t\t\tid_evento : idEvento,\r\n");
      out.write(" \t\t\tid_estatus : idEstatusEvento,\r\n");
      out.write(" \t\t\tfecha : fechaSeleccionada\r\n");
      out.write(" \t\t},\r\n");
      out.write(" \t\tsuccess: function(data) {\r\n");
      out.write("\r\n");
      out.write(" \t\t\t//$(\"#calendar\").empty();\r\n");
      out.write(" \t\t\tdebugger;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \t\t\tvar argEventos = eval(data);\r\n");
      out.write("\r\n");
      out.write(" \t\t\t$('#calendar').fullCalendar( 'removeEvents');\r\n");
      out.write(" \t\t    $('#calendar').fullCalendar('addEventSource', argEventos);\r\n");
      out.write("\r\n");
      out.write(" \t\t   if( $(\"#startDate\").val().length > 0){\r\n");
      out.write(" \t\t   \t$('#calendar').fullCalendar('gotoDate', new Date($(\"#startDate\").val().split('-')[1], $(\"#startDate\").val().split('-')[0], 1));\r\n");
      out.write(" \t\t   }\r\n");
      out.write(" \t\t\t//funcInicializaAgenda(argEventos, null);\r\n");
      out.write(" \t\t},\r\n");
      out.write(" \t\terror:function(exception){console.log('Exeption:'+exception); /*logSystem*/ swal(  'Error',  'Proceso no completado',  'error');}\r\n");
      out.write(" \t});\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("var funcObtenerAgendaTecnicos = function (){\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\tvar idCliente =  $(\"#id_cliente option:selected\").val();\r\n");
      out.write("\tvar idEvento =  $(\"#id_evento option:selected\").val();\r\n");
      out.write("\tvar idEstatusEvento =  $(\"#id_evento_status option:selected\").val();\r\n");
      out.write("\tvar fechaSeleccionada = $(\"#startDate\").val();\r\n");
      out.write("\r\n");
      out.write("\tif(fechaSeleccionada.length > 0){\r\n");
      out.write("\t\tfechaSeleccionada = fechaSeleccionada.split('-')[1];\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t$.ajax({\r\n");
      out.write(" \t\ttype:'POST',\r\n");
      out.write(" \t\turl :\"/SAO/AgendaSelectTecnicoServlet\",\r\n");
      out.write(" \t\tdata: {\r\n");
      out.write(" \t\t\tid_cliente : idCliente,\r\n");
      out.write(" \t\t\tid_evento : idEvento,\r\n");
      out.write(" \t\t\tid_estatus : idEstatusEvento,\r\n");
      out.write(" \t\t\tfecha : fechaSeleccionada\r\n");
      out.write(" \t\t},\r\n");
      out.write(" \t\tsuccess: function(data) {\r\n");
      out.write("\r\n");
      out.write(" \t\t\t//$(\"#calendar\").empty();\r\n");
      out.write(" \t\t\tdebugger;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \t\t\tvar argEventos = eval(data);\r\n");
      out.write("\r\n");
      out.write(" \t\t\t$('#calendar').fullCalendar( 'removeEvents');\r\n");
      out.write(" \t\t    $('#calendar').fullCalendar('addEventSource', argEventos);\r\n");
      out.write("\r\n");
      out.write(" \t\t   if( $(\"#startDate\").val().length > 0){\r\n");
      out.write(" \t\t   \t$('#calendar').fullCalendar('gotoDate', new Date($(\"#startDate\").val().split('-')[1], $(\"#startDate\").val().split('-')[0], 1));\r\n");
      out.write(" \t\t   }\r\n");
      out.write(" \t\t\t//funcInicializaAgenda(argEventos, null);\r\n");
      out.write(" \t\t},\r\n");
      out.write(" \t\terror:function(exception){console.log('Exeption:'+exception); /*logSystem*/ swal(  'Error',  'Proceso no completado',  'error');}\r\n");
      out.write(" \t});\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("var funcInicializaAgenda = function(argEventos, anio){\r\n");
      out.write("\tvar calendar = $('#calendar').fullCalendar({\r\n");
      out.write("        header: {\r\n");
      out.write("          left: 'prev,next today',\r\n");
      out.write("          center: 'title',\r\n");
      out.write("          right: 'month,agendaWeek,agendaDay'\r\n");
      out.write("        },\r\n");
      out.write("        //editable: false, // set this false\r\n");
      out.write("\r\n");
      out.write("        //lang: 'es',\r\n");
      out.write("        monthNames: ['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'],\r\n");
      out.write("        monthNamesShort: ['Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep','Oct','Nov','Dic'],\r\n");
      out.write("        dayNames: ['Domingo','Lunes','Martes','Miercoles','Jueves','Viernes','Sabado'],\r\n");
      out.write("        dayNamesShort: ['Dom','Lun','Mar','Mi','Jue','Vie','Sab'],\r\n");
      out.write("        buttonText: {\r\n");
      out.write("      \t  today: \"Hoy\",\r\n");
      out.write("     \t\t  month:    'mes',\r\n");
      out.write("  \t\t  week:     'semana',\r\n");
      out.write("  \t\t  day:      'dia',\r\n");
      out.write("   \t\t  list:     'lista'\r\n");
      out.write("        },\r\n");
      out.write("        height: 650,\r\n");
      out.write("        fixedWeekCount: false,\r\n");
      out.write("        selectable: true,\r\n");
      out.write("        selectHelper: true,\r\n");
      out.write("        eventClick: function(calEvent, jsEvent, view) {\r\n");
      out.write("\r\n");
      out.write("          $('#fc_edit').click();\r\n");
      out.write("\r\n");
      out.write("     \t\t$('#ID_EVENTO').val(calEvent.id_evento);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tif(calEvent.id_estatus != 5){\r\n");
      out.write("\t\t\t\t\t$('#title2').val(calEvent.evento);\r\n");
      out.write("\t\t\t\t\t$('#fecha').val(calEvent.fecha);\r\n");
      out.write("\t\t\t\t\t$('#cliente').val(calEvent.cliente);\r\n");
      out.write("\t\t\t\t//$('#sala').val(calEvent.sala);\r\n");
      out.write("\t\t\t\t//$('#interprete').val(calEvent.interprete);\r\n");
      out.write("\t\t\t\t\t$(\"#btnMemoEvento\").hide();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t$(\"#nFormAgenda1\").show();\r\n");
      out.write("\t\t\t\t\t$(\"#nFormAgenda2\").hide();\r\n");
      out.write("\t\t\t\t}else{\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(calEvent.id_tipo_eveto == 2){\r\n");
      out.write("\t\t\t\t\t\t$(\"#btnMemoEvento\").hide();\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t$(\"#btnMemoEvento\").show();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t$(\"#nFormAgenda1\").hide();\r\n");
      out.write("\t\t\t\t\tshowDatosEventoConfirmado(calEvent.id_evento);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("     \t\tshowInterpretes(calEvent.id_evento);\r\n");
      out.write("     \t\tshowFacturas(calEvent.id_evento);\r\n");
      out.write("\r\n");
      out.write("          categoryClass = $(\"#event_type\").val();\r\n");
      out.write("\r\n");
      out.write("          $(\".antosubmit2\").on(\"click\", function() {\r\n");
      out.write("            calEvent.title = $(\"#title2\").val();\r\n");
      out.write("\r\n");
      out.write("            calendar.fullCalendar('updateEvent', calEvent);\r\n");
      out.write("            $('.antoclose2').click();\r\n");
      out.write("          });\r\n");
      out.write("\r\n");
      out.write("          calendar.fullCalendar('unselect');\r\n");
      out.write("        },\r\n");
      out.write("\r\n");
      out.write("        editable: false,\r\n");
      out.write("\r\n");
      out.write("        events: argEventos\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function showInterpretes(param_id_evento) {\r\n");
      out.write("\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype:'POST',\r\n");
      out.write("\t\turl :\"/SAO/InterpretesAsignadosServlet\",\r\n");
      out.write("\t\tdata: {\r\n");
      out.write("\t\t\tID_EVENTO : param_id_evento\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tsuccess: function(data) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t$(\"#divInterpretesList\").empty();\r\n");
      out.write("\t\t\t$(\"#divInterpretesList\").append(data);\r\n");
      out.write("\r\n");
      out.write("\t\t\t$(\"#divInterpretesList\").hide();\r\n");
      out.write("// \t\t\t$(\"#divInterpretesAsignados\").show();\r\n");
      out.write("\t\t\t$(\"#divInterpretesList\").show();\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t//$(\"#divInterpretesDisponibles\").empty();\r\n");
      out.write("\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror:function(exception){console.log('Exeption:'+exception); /*logSystem*/ swal(  'Error',  'Proceso no completado',  'error');}\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function showDatosEventoConfirmado(param_id_evento) {\r\n");
      out.write("\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype:'POST',\r\n");
      out.write("\t\turl :\"/SAO/AgendaEventoFormServlet\",\r\n");
      out.write("\t\tdata: {\r\n");
      out.write("\t\t\tID_EVENTO : param_id_evento\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tsuccess: function(data) {\r\n");
      out.write("\t\t\t$(\"#nFormAgenda2\").html(data);\r\n");
      out.write("\r\n");
      out.write("\t\t\t$(\"#nFormAgenda2\").show();\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror:function(exception){console.log('Exeption:'+exception); /*logSystem*/ swal(  'Error',  'Proceso no completado',  'error');}\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function showFacturas(param_id_evento) {\r\n");
      out.write("\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype:'POST',\r\n");
      out.write("\t\turl :\"/SAO/FacturasSelectServlet\",\r\n");
      out.write("\t\tdata: {\r\n");
      out.write("\t\t\tID_EVENTO : param_id_evento\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tsuccess: function(data) {\r\n");
      out.write("\t\t\t$(\"#divFacturasList\").empty();\r\n");
      out.write("\t\t\t$(\"#divFacturasList\").append(data);\r\n");
      out.write("\r\n");
      out.write("\t\t\t$(\"#divFacturasList\").hide();\r\n");
      out.write("\t\t\t$(\"#divFacturasList\").show();\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror:function(exception){console.log('Exeption:'+exception); /*logSystem*/ swal(  'Error',  'Proceso no completado',  'error');}\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\n");
      out.write("\n");
      out.write("    <!-- jQuery -->\n");
      out.write("    <script src=\"../home/vendors/jquery/dist/jquery.min.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/jquery-ui.min.js\"></script>\n");
      out.write("\n");
      out.write("    <!-- Bootstrap -->\n");
      out.write("    <script src=\"../home/vendors/bootstrap/dist/js/bootstrap.min.js\"></script>\n");
      out.write("    <!-- FastClick -->\n");
      out.write("    <script src=\"../home/vendors/fastclick/lib/fastclick.js\"></script>\n");
      out.write("    <!-- NProgress -->\n");
      out.write("    <script src=\"../home/vendors/nprogress/nprogress.js\"></script>\n");
      out.write("    <!-- iCheck -->\n");
      out.write("    <script src=\"../home/vendors/iCheck/icheck.min.js\"></script>\n");
      out.write("    <!-- Datatables -->\n");
      out.write("    <script src=\"../home/vendors/datatables.net/js/jquery.dataTables.custom.js\"></script>\n");
      out.write("    <script src=\"../home/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js\"></script>\n");
      out.write("    <script src=\"../home/vendors/datatables.net-buttons/js/dataTables.buttons.min.js\"></script>\n");
      out.write("    <script src=\"../home/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js\"></script>\n");
      out.write("    <script src=\"../home/vendors/datatables.net-buttons/js/buttons.flash.min.js\"></script>\n");
      out.write("    <script src=\"../home/vendors/datatables.net-buttons/js/buttons.html5.min.js\"></script>\n");
      out.write("    <script src=\"../home/vendors/datatables.net-buttons/js/buttons.print.min.js\"></script>\n");
      out.write("    <script src=\"../home/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js\"></script>\n");
      out.write("    <script src=\"../home/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js\"></script>\n");
      out.write("    <script src=\"../home/vendors/datatables.net-responsive/js/dataTables.responsive.min.js\"></script>\n");
      out.write("    <script src=\"../home/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js\"></script>\n");
      out.write("    <script src=\"../home/vendors/datatables.net-scroller/js/dataTables.scroller.min.js\"></script>\n");
      out.write("    <script src=\"../home/vendors/jszip/dist/jszip.min.js\"></script>\n");
      out.write("    <script src=\"../home/vendors/pdfmake/build/pdfmake.min.js\"></script>\n");
      out.write("    <script src=\"../home/vendors/pdfmake/build/vfs_fonts.js\"></script>\n");
      out.write("\t<script src=\"../home/js/bootstrap-datepicker.js\"></script>\n");
      out.write("<!-- FullCalendar -->\n");
      out.write("    <script src=\"vendors/moment/min/moment.min.js\"></script>\n");
      out.write("    <script src=\"vendors/fullcalendar/dist/fullcalendar.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("    <!-- Custom Theme Scripts -->\n");
      out.write("    <script src=\"../home/build/js/custom.min.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    <!-- Datatables -->\n");
      out.write("    <script>\n");
      out.write("      $(document).ready(function() {\n");
      out.write("        var handleDataTableButtons = function() {\n");
      out.write("          if ($(\"#datatable-buttons\").length) {\n");
      out.write("            $(\"#datatable-buttons\").DataTable({\n");
      out.write("              dom: \"Bfrtip\",\n");
      out.write("              buttons: [\n");
      out.write("            \t  {\n");
      out.write("                      extend: \"copy\",\n");
      out.write("                      className: \"btn-sm\",\n");
      out.write("                      text : \"Copiar\"\n");
      out.write("                    },\n");
      out.write("                    {\n");
      out.write("                      extend: \"csv\",\n");
      out.write("                      className: \"btn-sm\",\n");
      out.write("                      text : \"Descargar CSV\"\n");
      out.write("                    },\n");
      out.write("                    {\n");
      out.write("                      extend: \"excel\",\n");
      out.write("                      className: \"btn-sm\",\n");
      out.write("                      text : \"Descargar Excel\"\n");
      out.write("                    },\n");
      out.write("                    {\n");
      out.write("                      extend: \"pdfHtml5\",\n");
      out.write("                      className: \"btn-sm\"\n");
      out.write("                    }\n");
      out.write("                    /*,\n");
      out.write("                    {\n");
      out.write("                      extend: \"print\",\n");
      out.write("                      className: \"btn-sm\"\n");
      out.write("                    },*/\n");
      out.write("              ],\n");
      out.write("              responsive: true\n");
      out.write("            });\n");
      out.write("          }\n");
      out.write("        };\n");
      out.write("\n");
      out.write("        TableManageButtons = function() {\n");
      out.write("          \"use strict\";\n");
      out.write("          return {\n");
      out.write("            init: function() {\n");
      out.write("              handleDataTableButtons();\n");
      out.write("            }\n");
      out.write("          };\n");
      out.write("        }();\n");
      out.write("\n");
      out.write("        $('#datatable').dataTable();\n");
      out.write("\n");
      out.write("        $('#datatable-keytable').DataTable({\n");
      out.write("          keys: true\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        $('#datatable-responsive').DataTable();\n");
      out.write("\n");
      out.write("        $('#datatable-scroller').DataTable({\n");
      out.write("          ajax: \"js/datatables/json/scroller-demo.json\",\n");
      out.write("          deferRender: true,\n");
      out.write("          scrollY: 380,\n");
      out.write("          scrollCollapse: true,\n");
      out.write("          scroller: true\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        $('#datatable-fixed-header').DataTable({\n");
      out.write("          fixedHeader: true\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        var $datatable = $('#datatable-checkbox');\n");
      out.write("\n");
      out.write("        $datatable.dataTable({\n");
      out.write("          'order': [[ 1, 'asc' ]],\n");
      out.write("          'columnDefs': [\n");
      out.write("            { orderable: false, targets: [0] }\n");
      out.write("          ]\n");
      out.write("        });\n");
      out.write("        $datatable.on('draw.dt', function() {\n");
      out.write("          $('input').iCheck({\n");
      out.write("            checkboxClass: 'icheckbox_flat-green'\n");
      out.write("          });\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        TableManageButtons.init();\n");
      out.write("      });\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("      $(window).load(function() {\n");
      out.write("\n");
      out.write("    \t  funcObternerEstatusEvento();\n");
      out.write("  \t\tfuncObternerComboEventoNombre();\n");
      out.write("  \t\tfuncObternerComboCliente();\n");
      out.write("\n");
      out.write("    \t  $('#startDate').datepicker( {\n");
      out.write("    \t\t  format: \"mm-yyyy\",\n");
      out.write("    \t\t    viewMode: \"months\",\n");
      out.write("    \t\t    minViewMode: \"months\"\n");
      out.write("    \t    });\n");
      out.write("\n");
      out.write("\n");
      out.write("        var date = new Date(),\n");
      out.write("            d = date.getDate(),\n");
      out.write("            m = date.getMonth(),\n");
      out.write("            y = date.getFullYear(),\n");
      out.write("            started,\n");
      out.write("            categoryClass;\n");
      out.write("\n");
      out.write("        var argEventos = ");
      out.print( Agenda.getAgendaEventoPorTecnico());
      out.write(";\n");
      out.write("\n");
      out.write("        funcInicializaAgenda(argEventos, null);\n");
      out.write("\n");
      out.write("              });\n");
      out.write("    </script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    <!-- /Datatables -->\n");
      out.write("  </body>\n");
      out.write("</html>\n");

    } else {
    	response.sendRedirect("../home/login.jsp");
    }
}catch(Exception _e){
	System.out.println("Error"+_e);
	_e.printStackTrace();
}

      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
