/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.82
 * Generated at: 2018-06-05 23:46:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.home;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.movemini.util.StringUtils;
import com.movemini.flexreports.ReportGenericForm;
import com.movemini.layers.session.SessionBean;
import com.movemini.simpleflexgrid.components.SelectList;
import com.movemini.data.OneRecordFactory;
import org.apache.tomcat.util.codec.binary.Base64;
import java.sql.*;
import java.io.*;
import java.util.List;
import java.util.ArrayList;
import com.movemini.config.HardCodeConstants;
import com.movemini.layers.session.SessionBean;
import com.movemini.layers.view.menu.RecordCounter;
import com.movemini.data.DataArray;
import com.movemini.data.Record;
import com.movemini.data.ConnectionWrapper;
import java.sql.DriverManager;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import java.sql.ResultSet;
import java.sql.Statement;

public final class flex_005freport_005fparams_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/home/adm_eventos_list_js.jsp", Long.valueOf(1527701487628L));
    _jspx_dependants.put("/home/commonSideBarMenu.jsp", Long.valueOf(1527701485317L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

	response.setHeader("Cache-Control","no-cache"); //HTTP 1.1
	response.setHeader("Pragma","no-cache"); //HTTP 1.0
	response.setDateHeader ("Expires", 0); //prevents caching at the proxy server

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

try
{
	boolean access = true;

	String id_report = request.getParameter("id_report");

	Record report = OneRecordFactory.getFirstRecord("select * from flex_report where id_report = " + id_report);

	ArrayList<Record> params = DataArray.getArrayList("select * from flex_report_param where id_report = " + id_report);

	ReportGenericForm formBean = new ReportGenericForm(request);



    if(access
//     		session.getAttribute("ID_USER") != null
    		) {





      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n");
      out.write("    <!-- Meta, title, CSS, favicons, etc. -->\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("\n");
      out.write("    <title>SAO - Reporte: ");
      out.print( report.get("name") );
      out.write("</title>\n");
      out.write("\n");
      out.write("    <!-- Bootstrap -->\n");
      out.write("    <link href=\"../home/vendors/bootstrap/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <!-- Font Awesome -->\n");
      out.write("    <link href=\"../home/vendors/font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\">\n");
      out.write("    <!-- NProgress -->\n");
      out.write("    <link href=\"../home/vendors/nprogress/nprogress.css\" rel=\"stylesheet\">\n");
      out.write("    <!-- iCheck -->\n");
      out.write("    <link href=\"../home/vendors/iCheck/skins/flat/green.css\" rel=\"stylesheet\">\n");
      out.write("    <!-- Datatables -->\n");
      out.write("    <link href=\"../home/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"../home/vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"../home/vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"../home/vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"../home/vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("\n");
      out.write("    <!-- Custom Theme Style -->\n");
      out.write("    <link href=\"../home/build/css/custom.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("\n");
      out.write("    <link href=\"../home/vendors/sweet_alert/sweetalert.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"../home/vendors/DateJS/prettify.css\" rel=\"stylesheet\" />\n");
      out.write("    <link href=\"../home/vendors/bootstrap-wysiwyg/css/style.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("     ");


                    	String message = "";

//                     	if(request.getParameter("idEventoChangeStatus") != null) {


//                     		String xid = request.getParameter("idEventoChangeStatus");
//                     		String xidStat = request.getParameter("idStatus");


//                     		ConnectionWrapper.staticExecuteUpdate("UPDATE evento SET id_evento_status = '" + xidStat + "' WHERE id_evento = '" + xid + "'");


//                     		message = "Se cambio el estatus del evento";
//                     	}


                    
      out.write("\n");
      out.write("\n");
      out.write("    <script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("\n");
      out.write("    function consultarInfo() {\n");
      out.write("\n");
      out.write("    \t//alert(\"1\");\n");
      out.write("\n");
      out.write("    \t ");

    	 	
	    	 StringBuilder sb = new StringBuilder();
			
			
    	 sb.append("id_report" + " : " + id_report + ",");

	    	 for(Record param : params) {

				String code = param.get("code");

				sb.append(code + " : $(\"#" + code + "\").val(),");
			}

			String strParams = StringUtils.removeLastChar(sb.toString());

		
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    \t//alert();\n");
      out.write("\n");
      out.write("     \t$.ajax({\n");
      out.write("     \t\ttype:'POST',\n");
      out.write("     \t\turl :\"/");
      out.print( HardCodeConstants.CONTEXT_PATH );
      out.write("/ReportGenericTableServlet\",\n");
      out.write("     \t\tdata: {\n");
      out.write("     \t\t\t");
      out.print( strParams );
      out.write("\n");
      out.write("     \t\t},\n");
      out.write("     \t\tsuccess: function(data) {\n");
      out.write("\n");
      out.write("     \t\t\t//alert(data);\n");
      out.write("\n");
      out.write("     \t\t\t$(\"#divReportTable\").empty();\n");
      out.write("     \t\t\t$(\"#divReportTable\").append(data);\n");
      out.write("\n");
      out.write("     \t\t\t$(\"#divReportTable\").hide();\n");
      out.write("     \t\t\t$(\"#divReportTable\").show();\n");
      out.write("     \t\t\t//$(\"#divReportTable\").toggle(200);\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("     \t\t},\n");
      out.write("     \t\terror:function(exception){console.log('Exeption:'+exception); /*logSystem*/ swal(  'Error',  'Proceso no completado',  'error');}\n");
      out.write("     \t});\n");
      out.write("\n");
      out.write("     }\n");
      out.write("\n");
      out.write("\tfunction generaReporteAgendaExcel(){\n");
      out.write("\n");
      out.write("\t\tdocument.getElementById(\"formReport\").submit();\n");
      out.write("\t\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("      function exportar() {\n");
      out.write("\n");
      out.write("  \t\tvar paramsGetString = \"id_report=");
      out.print(id_report);
      out.write("&\";\n");
      out.write("\n");
      out.write("      \t ");

  	    	 //StringBuilder sb2 = new StringBuilder();

  	    	 for(Record param : params) {

  				String code = param.get("code");

  				//sb2.append(code + " : $(\"#" + code + "\").val(),");

  				
      out.write("\n");
      out.write("  \t\t\t\t\tparamsGetString += \"");
      out.print( code );
      out.write("=\" + $(\"#");
      out.print( code );
      out.write("\").val() + \"&\";\n");
      out.write("  \t\t\t\t");


  			}
	
      out.write("\n");
      out.write("\n");
      out.write("\t//alert(\"/");
      out.print( HardCodeConstants.CONTEXT_PATH );
      out.write("/ReportGenericCSVServlet?\" + paramsGetString);\n");
      out.write("\n");
      out.write("  \t\twindow.location = \"/");
      out.print( HardCodeConstants.CONTEXT_PATH );
      out.write("/ReportGenericCSVServlet?\" + paramsGetString;\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("       }\n");
      out.write("\n");
      out.write("    </script>\n");
      out.write("\n");
      out.write("  </head>\n");
      out.write("  <body class=\"nav-md\">\n");
      out.write("\n");
      out.write("    <div class=\"container body\">\n");
      out.write("      <div class=\"main_container\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("      \t");
      out.write('\n');
      out.write('\n');

	response.setHeader("Cache-Control","no-cache"); //HTTP 1.1
	response.setHeader("Pragma","no-cache"); //HTTP 1.0
	response.setDateHeader ("Expires", 0); //prevents caching at the proxy server

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");




// 	Connection connx = ConnectionWrapper.getDirectJDBCConnection();



Record user = SessionBean.getInstance(request).getUser();



// 	List<String> lstMenuPadres = new ArrayList<String>();
// 	String Role = "";

// 	Statement stScreen = connx.createStatement();
// 	ResultSet rsScreen = stScreen.executeQuery("SELECT * FROM screen_role WHERE ID_ROLE = '"+session.getAttribute("ID_ROLE")+"'");
// 	while(rsScreen.next()){
// 		Statement stName = connx.createStatement();
// 		ResultSet rsName = stName.executeQuery("SELECT * FROM menu WHERE ID_SCREEN = '"+rsScreen.getInt(1)+"' and ID_PADRE = 0 AND ID_ROLE ="+session.getAttribute("ID_ROLE")+" ORDER BY ID_ORDER, ID");
// 		while(rsName.next()){
// 			lstMenuPadres.add(rsName.getString("NAME"));
// 		}
// 	}



	ArrayList<Record> menuParents = DataArray.getArrayList("SELECT * FROM ss_menu WHERE id_menu_padre = 0 AND accesos LIKE '%" + user.get("id_rol") + "%' ORDER BY id_orden");




// 	Statement stR = connx.createStatement();
// 	ResultSet rsR = stR.executeQuery("SELECT * FROM role WHERE ID = "+session.getAttribute("ID_ROLE")+"");
// 	while(rsR.next()){
// 		Role = rsR.getString(2);
// 	}




// 	String[] dtaUser = new String[10];
// 	String imagen = "";
// 	String imagenUser = "";
// 	Statement stUs = connx.createStatement();
// 	//ResultSet rsUs = stUs.executeQuery("SELECT * FROM user WHERE ID = "+session.getAttribute("ID_USER")+"");
// 	while(rsUs.next()){
// // 		dtaUser[0] = rsUs.getString(1);
// // 		dtaUser[1] = rsUs.getString(2);
// // 		dtaUser[2] = rsUs.getString(3);
// // 		dtaUser[3] = rsUs.getString(4);
// // 		dtaUser[4] = rsUs.getString(5);
// // 		dtaUser[5] = rsUs.getString(6);
// // 		dtaUser[6] = rsUs.getString(7);
// // 		dtaUser[7] = rsUs.getString(8);
// 		if(rsUs.getString(9)!= null){
// 			imagen = rsUs.getString(9);
// 		}
// 		else{
// 			Statement stDef = connx.createStatement();
// 			ResultSet rsDef = stDef.executeQuery("SELECT * FROM configuracion WHERE id_conf = 3");
// 			while(rsDef.next()){
// 				imagen = rsDef.getString(3);
// 			}
// 		}
// 		dtaUser[9] = rsUs.getString(10);
// 	}




// 	Statement stEditEvento = connx.createStatement();
// 	ResultSet rsEditEvento = stEditEvento.executeQuery("SELECT * FROM evento WHERE ID = "+request.getParameter("ID_EVENTO")+"");
// 	String[] lstEvento = new String[12];
// 	while(rsEditEvento.next()){
// 		lstEvento[0] =  rsEditEvento.getString(1);
// 		lstEvento[1] =  rsEditEvento.getString(2);
// 		lstEvento[2] =  rsEditEvento.getString(3);
// 		lstEvento[3] =  rsEditEvento.getString(4);
// 		lstEvento[4] =  rsEditEvento.getString(5);
// 		lstEvento[5] =  rsEditEvento.getString(6);
// 		lstEvento[6] =  rsEditEvento.getString(7);
// 	}










      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("      <div class=\"col-md-3 left_col\">\n");
      out.write("          <div class=\"left_col scroll-view\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t \t\t<div class=\"navbar nav_title\" style=\"border: 0;\">\n");
      out.write("\t\t              <a href=\"main.jsp\" class=\"site_title\"> <span>SAO</span></a>\n");
      out.write("\t\t            </div>\n");
      out.write("\t\t            <div class=\"clearfix\"></div>\n");
      out.write("\n");
      out.write("\t\t           <!--\n");
      out.write("\t\t            -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t            <!-- menu profile quick info -->\n");
      out.write("\t\t            <div class=\"profile\">\n");
      out.write("\t\t              <div class=\"profile_pic\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t              <img id='profileImg1' src=\"/");
      out.print( HardCodeConstants.CONTEXT_PATH );
      out.write("/ProfilePhotoServlet\" width=\"40%\" height=\"40%\" class=\"img-circle profile_img\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t              </div>\n");
      out.write("\t\t              <div class=\"profile_info\">\n");
      out.write("\t\t                <!--<span>");
      out.print( user.get("rol_name") );
      out.write("</span>-->\n");
      out.write("\t\t                <h2>");
      out.print( user.get("nombre") );
      out.print(" ");
      out.print( user.get("apellido") );
      out.write("</h2>\n");
      out.write("\t\t              </div>\n");
      out.write("\t\t            </div>\n");
      out.write("\t\t            <!-- /menu profile quick info -->\n");
      out.write("\n");
      out.write("\t\t            <br />\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t<!-- sidebar menu -->\n");
      out.write("\t\t            <div id=\"sidebar-menu\" class=\"main_menu_side hidden-print main_menu\">\n");
      out.write("\t\t              <div class=\"menu_section\">\n");
      out.write("\t\t                <!-- <h3>Menu</h3>-->\n");
      out.write("\t\t                <br>\n");
      out.write("\t\t                <br>\n");
      out.write("\t\t                <br>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t                <ul class=\"nav side-menu\">\n");
      out.write("\t\t                ");




		                for (Record recordParent: menuParents) {

		                	//Statement st1 = connx.createStatement();
		                    //ResultSet rs1 = st1.executeQuery("SELECT * FROM menu m WHERE m.NAME = '"+item+"' AND ID_ROLE = "+session.getAttribute("ID_ROLE")+" ORDER BY ID_ORDER, ID");

		                    
      out.write("\n");
      out.write("\t\t                \t<li><a>\n");
      out.write("\t\t                \t\t\t<i class=\"");
      out.print(recordParent.getString("class") );
      out.write("\"></i>\n");
      out.write("\t\t                \t\t\t\t\t");
      out.print(recordParent.get("nombre") );
      out.write("\n");
      out.write("\t\t                \t\t\t\t\t<span class=\"fa fa-chevron-down\"></span>\n");
      out.write("\t\t                \t\t</a>\n");
      out.write("\t\t                \t\t<ul class=\"nav child_menu\">\n");
      out.write("\t\t                \t\t");





		                	ArrayList<Record> menuChilds = DataArray.getArrayList("SELECT * FROM ss_menu WHERE id_menu_padre = " + recordParent.get("id_menu") + " AND accesos LIKE '%" + user.get("id_rol") + "%' ORDER BY id_orden");

		                	for (Record recordChild: menuChilds) {
		                    	
      out.write("\n");
      out.write("\n");
      out.write("\t\t                \t\t\t<li class=\"");
      out.print(recordChild.getString("class") );
      out.write("\"><a href=\"");
      out.print(recordChild.getString("url"));
      out.write("\">\n");
      out.write("\t\t                \t\t\t");
      out.print( recordChild.getString("nombre") );
      out.write("\n");
      out.write("\t\t                \t\t\t");
      out.print( RecordCounter.getCount(user.get("id_usuario"), recordChild.get("url")) );
      out.write("\n");
      out.write("\t\t                \t\t\t</a></li>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t                \t\t\t");

		                    }

		                    
      out.write("\n");
      out.write("\t\t                    \t</ul>\n");
      out.write("\t\t                   \t</li>\n");
      out.write("\t\t                    ");

		                }
		                
      out.write("\n");
      out.write("\t\t                </ul>\n");
      out.write("\t\t              </div>\n");
      out.write("\t\t            </div>\n");
      out.write("\t\t            <!-- /sidebar menu -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t            <!-- /menu footer buttons -->\n");
      out.write("\t\t            <div class=\"sidebar-footer hidden-small\">\n");
      out.write("\t\t            <!--\n");
      out.write("\t\t              <a data-toggle=\"tooltip\" data-placement=\"top\" title=\"Settings\">\n");
      out.write("\t\t                <span class=\"glyphicon glyphicon-cog\" aria-hidden=\"true\"></span>\n");
      out.write("\t\t              </a>\n");
      out.write("\t\t              <a data-toggle=\"tooltip\" data-placement=\"top\" title=\"FullScreen\">\n");
      out.write("\t\t                <span class=\"glyphicon glyphicon-fullscreen\" aria-hidden=\"true\"></span>\n");
      out.write("\t\t              </a>\n");
      out.write("\t\t              <a data-toggle=\"tooltip\" data-placement=\"top\" title=\"Lock\">\n");
      out.write("\t\t                <span class=\"glyphicon glyphicon-eye-close\" aria-hidden=\"true\"></span>\n");
      out.write("\t\t              </a>\n");
      out.write("\t\t               -->\n");
      out.write("\t\t              <a data-toggle=\"tooltip\" data-placement=\"top\" title=\"Logout\" href=\"../home/logOut.jsp\">\n");
      out.write("\t\t                <span class=\"glyphicon glyphicon-off\" aria-hidden=\"true\"></span>\n");
      out.write("\t\t              </a>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<!--\t<a href=\"javascript:void(0);\" data-toggle=\"tooltip\" onclick=\"alert()\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"glyphicon glyphicon-bell\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"badge bg-green\">6</span>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t</a> -->\n");
      out.write("\n");
      out.write("\t\t            </div>\n");
      out.write("\t\t            <!-- /menu footer buttons -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("        <!-- top navigation -->\n");
      out.write("        <div class=\"top_nav\">\n");
      out.write("          <div class=\"nav_menu\">\n");
      out.write("            <nav>\n");
      out.write("              <div class=\"nav toggle\">\n");
      out.write("                <a id=\"menu_toggle\"><i class=\"fa fa-bars\"></i></a>\n");
      out.write("              </div>\n");
      out.write("\n");
      out.write("              <ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("                <li class=\"\">\n");
      out.write("                  <a href=\"javascript:;\" class=\"user-profile dropdown-toggle\" data-toggle=\"dropdown\" aria-expanded=\"false\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                    <img id='profileImg2' src=\"/");
      out.print( HardCodeConstants.CONTEXT_PATH );
      out.write("/ProfilePhotoServlet\" width=\"40%\" height=\"40%\">\n");
      out.write("\n");
      out.write("                    ");
      out.print( user.get("nombre") );
      out.print(" ");
      out.print( user.get("apellido") );
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                    <span class=\" fa fa-angle-down\"></span>\n");
      out.write("                  </a>\n");
      out.write("                  <ul class=\"dropdown-menu dropdown-usermenu pull-right\">\n");
      out.write("                    <li><a href=\"../home/logOut.jsp\"><i class=\"fa fa-sign-out pull-right\"></i>Salir </a></li>\n");
      out.write("\n");
      out.write("                  </ul>\n");
      out.write("                </li>\n");
      out.write("\n");
      out.write("              </ul>\n");
      out.write("            </nav>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- /top navigation -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");



// ConnectionWrapper.closeAll(rsScreen, stScreen, rsR, stR, connx);



      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("         <div class=\"right_col\" role=\"main\">\n");
      out.write("          <div class=\"\">\n");
      out.write("            <div class=\"page-title\">\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"clearfix\"></div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"col-md-12 col-sm-12 col-xs-12\">\n");
      out.write("                <div class=\"x_panel\">\n");
      out.write("                  <div class=\"x_title\">\n");
      out.write("                    <p><strong>Reporte: ");
      out.print( report.get("name") );
      out.write("</strong> </p>\n");
      out.write("                    <ul class=\"nav navbar-right panel_toolbox\">\n");
      out.write("                    </ul>\n");
      out.write("                    <div class=\"clearfix\"></div>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"x_content\">\n");
      out.write("                    <p class=\"text-muted font-13 m-b-30\">\n");
      out.write("\n");
      out.write("                   ");
      out.print( report.get("description") );
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                    </p>\n");
      out.write("\n");
      out.write("\n");
      out.write("                    <div class=\"x_panel\">\n");
      out.write("\t\t\t\t\t\t\t<form id=\"formReport\" name=\"formReport\" action=\"");
      out.print(request.getContextPath());
      out.write("/ReportAgendaExcel\" method=\"get\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"x_content\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-8 col-sm-8 col-xs-8\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      out.print( formBean.getFormHtml());
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-6 col-sm-6 col-xs-12\" >\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-6 col-sm-6 col-xs-12\" >\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div align=\"center\" style=\"vertical-align: middle;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											//Argumel 30/05/2018
											if(id_report.equals("11")){
										
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"button\" class=\"btn btn-info\" value=\"Consultar\" onclick=\"javascript:generaReporteAgendaExcel()\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											}else{
										
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a type=\"button\" class=\"btn btn-info\" onclick=\"consultarInfo()\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tConsultar\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											}
										
      out.write("\t\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a type=\"button\" class=\"btn btn-primary\" onclick=\"exportar()\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tExportar\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                    <div align=\"left\">\n");
      out.write("\n");
      out.write("                    <div id=\"divReportTable\" style=\"overflow:auto;\">\n");
      out.write("                      </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                  \t<p class=\"text-muted font-13 m-b-30\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write('\n');
      out.write("\n");
      out.write("<!-- //                       for(Record param : params) { -->\n");
      out.write('\n');
      out.write('\n');
      out.write("\n");
      out.write("<!-- //                       } -->\n");
      out.write("\n");
      out.write("<!--                       <input type=\"submit\"> -->\n");
      out.write("\n");
      out.write("                    </p>\n");
      out.write("                    <br>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("     </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("               <footer>\n");
      out.write("          <div class=\"pull-right\">\n");
      out.write("\n");
      out.write("          </div>\n");
      out.write("          <div class=\"clearfix\"></div>\n");
      out.write("        </footer>\n");
      out.write("        <!-- /footer content -->\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    <!-- jQuery -->\n");
      out.write("    <script src=\"../home/vendors/jquery/dist/jquery.min.js\"></script>\n");
      out.write("    <!-- Bootstrap -->\n");
      out.write("    <script src=\"../home/vendors/bootstrap/dist/js/bootstrap.min.js\"></script>\n");
      out.write("    <!-- FastClick -->\n");
      out.write("    <script src=\"../home/vendors/fastclick/lib/fastclick.js\"></script>\n");
      out.write("    <!-- NProgress -->\n");
      out.write("    <script src=\"../home/vendors/nprogress/nprogress.js\"></script>\n");
      out.write("    <!-- iCheck -->\n");
      out.write("    <script src=\"../home/vendors/iCheck/icheck.min.js\"></script>\n");
      out.write("    <!-- Datatables -->\n");
      out.write("    <script src=\"../home/vendors/datatables.net/js/jquery.dataTables.custom.js\"></script>\n");
      out.write("    <script src=\"../home/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js\"></script>\n");
      out.write("    <script src=\"../home/vendors/datatables.net-buttons/js/dataTables.buttons.min.js\"></script>\n");
      out.write("    <script src=\"../home/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js\"></script>\n");
      out.write("    <script src=\"../home/vendors/datatables.net-buttons/js/buttons.flash.min.js\"></script>\n");
      out.write("    <script src=\"../home/vendors/datatables.net-buttons/js/buttons.html5.min.js\"></script>\n");
      out.write("    <script src=\"../home/vendors/datatables.net-buttons/js/buttons.print.min.js\"></script>\n");
      out.write("    <script src=\"../home/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js\"></script>\n");
      out.write("    <script src=\"../home/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js\"></script>\n");
      out.write("    <script src=\"../home/vendors/datatables.net-responsive/js/dataTables.responsive.min.js\"></script>\n");
      out.write("    <script src=\"../home/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js\"></script>\n");
      out.write("    <script src=\"../home/vendors/datatables.net-scroller/js/dataTables.scroller.min.js\"></script>\n");
      out.write("    <script src=\"../home/vendors/jszip/dist/jszip.min.js\"></script>\n");
      out.write("    <script src=\"../home/vendors/pdfmake/build/pdfmake.min.js\"></script>\n");
      out.write("    <script src=\"../home/vendors/pdfmake/build/vfs_fonts.js\"></script>\n");
      out.write("\n");
      out.write("    <!-- Custom Theme Scripts -->\n");
      out.write("    <script src=\"../home/build/js/custom.min.js\"></script>\n");
      out.write("\n");

	response.setHeader("Cache-Control","no-cache"); //HTTP 1.1
	response.setHeader("Pragma","no-cache"); //HTTP 1.0
	response.setDateHeader ("Expires", 0); //prevents caching at the proxy server

      out.write('\n');
      out.write('\n');

	// OK

      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("var idEventoGlobal = 0;\n");
      out.write("var idDetalleGlobal = 0;\n");
      out.write("\n");
      out.write("function PopupCenter(url, title, w, h) {\n");
      out.write("    // Fixes dual-screen position                         Most browsers      Firefox\n");
      out.write("    var dualScreenLeft = window.screenLeft != undefined ? window.screenLeft : screen.left;\n");
      out.write("    var dualScreenTop = window.screenTop != undefined ? window.screenTop : screen.top;\n");
      out.write("\n");
      out.write("    var width = window.innerWidth ? window.innerWidth : document.documentElement.clientWidth ? document.documentElement.clientWidth : screen.width;\n");
      out.write("    var height = window.innerHeight ? window.innerHeight : document.documentElement.clientHeight ? document.documentElement.clientHeight : screen.height;\n");
      out.write("\n");
      out.write("    var left = ((width / 2) - (w / 2)) + dualScreenLeft;\n");
      out.write("    var top = ((height / 2) - (h / 2)) + dualScreenTop;\n");
      out.write("    var newWindow = window.open(url, title, 'scrollbars=yes, width=' + w + ', height=' + h + ', top=' + top + ', left=' + left);\n");
      out.write("\n");
      out.write("    // Puts focus on the newWindow\n");
      out.write("    if (window.focus) {\n");
      out.write("        newWindow.focus();\n");
      out.write("    }\n");
      out.write("}\n");
      out.write("\n");
      out.write("function previewFactura(f_id,idEvento) {\n");
      out.write("\tPopupCenter('/SAO/home/factura_html.jsp?ID_EVENTO='+idEvento+'&idFactura='+f_id,'Vista Previa','900','500');\n");
      out.write("}\n");
      out.write("\n");
      out.write("function previewFacturaPDF(f_id,idEvento)\n");
      out.write("{\n");
      out.write("    PopupCenter('/SAO/home/factura_pdf.jsp?ID_EVENTO='+idEvento+'&idFactura='+f_id,'Vista Previa','900','500');\n");
      out.write("}\n");
      out.write("\n");
      out.write("function montosFactura(f_id){\n");
      out.write("\n");
      out.write("    $.ajax({\n");
      out.write("       url :\"/SAO/MontoFacturaSelectServlet\" ,\n");
      out.write("       type: \"post\",\n");
      out.write("       data : { ID_FACTURA: f_id},\n");
      out.write("       success:function (data){\n");
      out.write("            $(\"#divFacturaPreview\").html(data);\n");
      out.write("       },\n");
      out.write("\n");
      out.write("\n");
      out.write("    });\n");
      out.write("    //$('#modalFacturaPreview').modal(\"show\");\n");
      out.write("\n");
      out.write("}\n");
      out.write("\n");
      out.write("function deleteFactura(p_id,idEvento) {\n");
      out.write("\n");
      out.write("\t$.ajax({\n");
      out.write("\t\ttype:'POST',\n");
      out.write("\t\turl :\"/SAO/EventoFacturaDelete\",\n");
      out.write("\t\tdata: {\n");
      out.write("\t\t\tkey : p_id\n");
      out.write("\t\t},\n");
      out.write("\t\tsuccess: function(data) {\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t   mostrarModalFacturas(idEvento)\t;\n");
      out.write("\n");
      out.write("\t\t},\n");
      out.write("\t\terror:function(exception){console.log('Exeption:'+exception); /*logSystem*/ swal(  'Error',  'Proceso no completado',  'error');}\n");
      out.write("\t});\n");
      out.write("\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("function deleteDetalleFactura(p_id,idFactura) {\n");
      out.write("\n");
      out.write("\t$.ajax({\n");
      out.write("\t\ttype:'POST',\n");
      out.write("\t\turl :\"/SAO/FacturaDetalleDelete\",\n");
      out.write("\t\tdata: {\n");
      out.write("\t\t\tkey : p_id\n");
      out.write("\t\t},\n");
      out.write("\t\tsuccess: function(data) {\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t   mostrarModalDetalleFacturas(idFactura,idEventoGlobal)\t;\n");
      out.write("\n");
      out.write("\t\t},\n");
      out.write("\t\terror:function(exception){console.log('Exeption:'+exception); /*logSystem*/ swal(  'Error',  'Proceso no completado',  'error');}\n");
      out.write("\t});\n");
      out.write("\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("function deleteMonto(p_id,idFactura) {\n");
      out.write("\n");
      out.write("\t$.ajax({\n");
      out.write("\t\ttype:'POST',\n");
      out.write("\t\turl :\"/SAO/MontoFacturaDelete\",\n");
      out.write("\t\tdata: {\n");
      out.write("\t\t\tkey : p_id\n");
      out.write("\t\t},\n");
      out.write("\t\tsuccess: function(data) {\n");
      out.write("\n");
      out.write("            montosFactura(idFactura);\n");
      out.write("\n");
      out.write("\t\t},\n");
      out.write("\t\terror:function(exception){console.log('Exeption:'+exception); /*logSystem*/ swal(  'Error',  'Proceso no completado',  'error');}\n");
      out.write("\t});\n");
      out.write("\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("function nuevoMonto(idFactura){\n");
      out.write("\n");
      out.write("     $.ajax({\n");
      out.write("\t\t\ttype:'POST',\n");
      out.write("\t\t\turl :\"/SAO/AddMontoFacturaServlet\",\n");
      out.write("\t\t\tdata: {\n");
      out.write("\t\t\t\tID_FACTURA : idFactura\n");
      out.write("\t\t\t},\n");
      out.write("\t\t\tsuccess: function(data) {\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t   montosFactura(idFactura);\n");
      out.write("\t\t\t\t actualizarVistaPreviaEF(idFactura);\n");
      out.write("\n");
      out.write("\t\t\t},\n");
      out.write("\t\t\terror:function(exception){console.log('Exeption:'+exception); /*logSystem*/ swal(  'Error',  'Proceso no completado',  'error');}\n");
      out.write("\t\t});\n");
      out.write("}\n");
      out.write("\n");
      out.write("function nuevaFactura(idEvento){\n");
      out.write("\n");
      out.write("     $.ajax({\n");
      out.write("\t\t\ttype:'POST',\n");
      out.write("\t\t\turl :\"/SAO/AddEventoFacturaServlet\",\n");
      out.write("\t\t\tdata: {\n");
      out.write("\t\t\t\tID_EVENTO : idEvento\n");
      out.write("\t\t\t},\n");
      out.write("\t\t\tsuccess: function(data) {\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t   mostrarModalFacturas(idEvento)\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t},\n");
      out.write("\t\t\terror:function(exception){console.log('Exeption:'+exception); /*logSystem*/ swal(  'Error',  'Proceso no completado',  'error');}\n");
      out.write("\t\t});\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("function nuevoDetalleFactura(idFactura){\n");
      out.write("\n");
      out.write("     $.ajax({\n");
      out.write("\t\t\ttype:'POST',\n");
      out.write("\t\t\turl :\"/SAO/AddEventoDetalleFacturaServlet\",\n");
      out.write("\t\t\tdata: {\n");
      out.write("\t\t\t\tID_FACTURA : idFactura\n");
      out.write("\t\t\t},\n");
      out.write("\t\t\tsuccess: function() {\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t   mostrarModalDetalleFacturas(idFactura,$(\"#auxIdEvento\").val()\t);\n");
      out.write("\t\t\t\t \tactualizarVistaPreviaEF(idFactura);\n");
      out.write("\n");
      out.write("\t\t\t},\n");
      out.write("\t\t\terror:function(exception){console.log('Exeption:'+exception); /*logSystem*/ swal(  'Error',  'Proceso no completado',  'error');}\n");
      out.write("\t\t});\n");
      out.write("}\n");
      out.write("\n");
      out.write("function showDatosEventoConfirmado(param_id_evento) {\n");
      out.write("\n");
      out.write("\t$.ajax({\n");
      out.write("\t\ttype:'POST',\n");
      out.write("\t\turl :\"/SAO/AgendaEventoFormServlet\",\n");
      out.write("\t\tdata: {\n");
      out.write("\t\t\tID_EVENTO : param_id_evento\n");
      out.write("\t\t},\n");
      out.write("\t\tsuccess: function(data) {\n");
      out.write("\t\t\t$(\"#nFormAgenda2\").html(data);\n");
      out.write("\n");
      out.write("\t\t\t$(\"#nFormAgenda2\").show();\n");
      out.write("\t\t},\n");
      out.write("\t\terror:function(exception){console.log('Exeption:'+exception); /*logSystem*/ swal(  'Error',  'Proceso no completado',  'error');}\n");
      out.write("\t});\n");
      out.write("\n");
      out.write("}\n");
      out.write("\n");
      out.write("function mostrarModalDetalleFacturas(idFactura,idEvento){\n");
      out.write("\tidDetalleGlobal = idFactura;\n");
      out.write("\tidEventoGlobal = idEvento;\n");
      out.write("\t$(\"#auxIdEvento\").val(idEvento);\n");
      out.write("\t$(\"#modalMemoFacturaDetalle\").modal('show');\n");
      out.write("\tmontosFactura(idFactura);\n");
      out.write("\tshowDatosEventoConfirmado(idEvento);\n");
      out.write("\tactualizarVistaPreviaEF(idFactura);\n");
      out.write("\t/*\n");
      out.write("\t$.ajax({\n");
      out.write("\t\ttype:'POST',\n");
      out.write("\t\turl :\"/SAO/FacturaDetalleEventoSelectServlet\",\n");
      out.write("\t\tdata: {\n");
      out.write("\t\t\tID_FACTURA : idFactura\n");
      out.write("\t\t},\n");
      out.write("\t\tsuccess: function(data) {\n");
      out.write("\n");
      out.write("\t\t\t$(\"#divCapturaFacturaDetalle\").empty();\n");
      out.write("\t\t\t$(\"#divCapturaFacturaDetalle\").append(data);\n");
      out.write("\n");
      out.write("\t\t\t$(\"#divCapturaFacturaDetalle\").hide();\n");
      out.write("//\t \t\t\t$(\"#divInterpretesAsignados\").show();\n");
      out.write("\t\t\t$(\"#divCapturaFacturaDetalle\").show();\n");
      out.write("\t\t\t\t$(\"#datatable-but\").DataTable({\n");
      out.write("\t\t\t\t\t\t\t\t\tdom: \"Bfrtip\",\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\tresponsive: true\n");
      out.write("\t\t\t\t\t\t\t\t});\n");
      out.write("\t\t\t\tactualizarVistaPreviaEF(idFactura);\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t},\n");
      out.write("\t\terror:function(exception){console.log('Exeption:'+exception); /*logSystemswal(  'Error',  'Proceso no completado',  'error');}\n");
      out.write("\t});\n");
      out.write("*/\n");
      out.write("\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("function updateFactura(p_key, object, p_campo) {\n");
      out.write("\n");
      out.write("\t//alert(object.value);\n");
      out.write("\n");
      out.write("\t$.ajax({\n");
      out.write("\t\ttype:'POST',\n");
      out.write("\t\turl :\"/SAO/FacturaUpdateServlet\",\n");
      out.write("\t\tdata: {\n");
      out.write("\t\t\tkey : p_key,\n");
      out.write("\t\t\tvalor: object.value,\n");
      out.write("\t\t\tcampo: p_campo\n");
      out.write("\t\t},\n");
      out.write("\t\tsuccess: function(data) {\n");
      out.write("\n");
      out.write("\t\t\t/*$(\"#divOutput\").empty();\n");
      out.write("\t\t\t$(\"#divOutput\").append(data);\n");
      out.write("\n");
      out.write("\t\t\t$(\"#divOutput\").hide();\n");
      out.write("\t\t\t$(\"#divOutput\").show();*/\n");
      out.write("\n");
      out.write("\t\t},\n");
      out.write("\t\terror:function(exception){console.log('Exeption:'+exception); /*logSystem*/ swal(  'Error',  'Proceso no completado',  'error');}\n");
      out.write("\t});\n");
      out.write("\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("function updateDetalleFactura(p_key, object, p_campo,idFactura) {\n");
      out.write("\tidDetalleGlobal = idFactura;\n");
      out.write("\t//alert(object.value);\n");
      out.write("\n");
      out.write("\t$.ajax({\n");
      out.write("\t\ttype:'POST',\n");
      out.write("\t\turl :\"/SAO/FacturaDetalleUpdateServlet\",\n");
      out.write("\t\tdata: {\n");
      out.write("\t\t\tkey : p_key,\n");
      out.write("\t\t\tvalor: object.value,\n");
      out.write("\t\t\tcampo: p_campo\n");
      out.write("\t\t},\n");
      out.write("\t\tsuccess: function(data) {\n");
      out.write("\n");
      out.write("\t\t\t/*$(\"#divOutput\").empty();\n");
      out.write("\t\t\t$(\"#divOutput\").append(data);\n");
      out.write("\n");
      out.write("\t\t\t$(\"#divOutput\").hide();\n");
      out.write("\t\t\t$(\"#divOutput\").show();*/\n");
      out.write("\t\t\tactualizarVistaPreviaEF(idFactura);\n");
      out.write("\n");
      out.write("\t\t},\n");
      out.write("\t\terror:function(exception){console.log('Exeption:'+exception); /*logSystem*/ swal(  'Error',  'Proceso no completado',  'error');}\n");
      out.write("\t});\n");
      out.write("\n");
      out.write("}\n");
      out.write("\n");
      out.write("function updateMonto(p_key, object, p_campo) {\n");
      out.write("\n");
      out.write("\t//alert(object.value);\n");
      out.write("\n");
      out.write("\t$.ajax({\n");
      out.write("\t\ttype:'POST',\n");
      out.write("\t\turl :\"/SAO/MontoUpdateServlet\",\n");
      out.write("\t\tdata: {\n");
      out.write("\t\t\tkey : p_key,\n");
      out.write("\t\t\tvalor: object.value,\n");
      out.write("\t\t\tcampo: p_campo\n");
      out.write("\t\t},\n");
      out.write("\t\tsuccess: function(data) {\n");
      out.write("\n");
      out.write("\t\t\t/*$(\"#divOutput\").empty();\n");
      out.write("\t\t\t$(\"#divOutput\").append(data);\n");
      out.write("\n");
      out.write("\t\t\t$(\"#divOutput\").hide();\n");
      out.write("\t\t\t$(\"#divOutput\").show();*/\n");
      out.write("\t\t\tactualizarVistaPreviaEF(idDetalleGlobal);\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t},\n");
      out.write("\t\terror:function(exception){console.log('Exeption:'+exception); /*logSystem*/ swal(  'Error',  'Proceso no completado',  'error');}\n");
      out.write("\t});\n");
      out.write("\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("function mostrarModalMemoServicio(idEvento){\n");
      out.write("\n");
      out.write("\tidEventoGlobal = idEvento;\n");
      out.write("\tdebugger;\n");
      out.write("\t  $(\"#modalMemoServicio\").modal('show');\n");
      out.write("\n");
      out.write("\t  $(\"#divCapturaMemoEvento\").empty();\n");
      out.write("\t  $(\"#divVistaPrevia\").empty();\n");
      out.write("\n");
      out.write("\t  $('#editorCliente').empty();\n");
      out.write("\t  $('#editorOmni').empty();\n");
      out.write("\n");
      out.write("\t  obtenerMemoServicio(idEvento);\n");
      out.write("\n");
      out.write("\t  obtenerCorreoContactoCliente(idEvento, \"1\");\n");
      out.write("\t\t");
 // Ver si son lo correos son los de omnilingua o de los interpretes
		 
      out.write("\n");
      out.write("\t  \tobtenerCorreoContactoCliente(idEvento, \"2\");\n");
      out.write("\t\tobtenerCorreoContactoCliente(idEvento, \"3\");\n");
      out.write("\n");
      out.write("\t  obtenerNombreEvento(idEvento);\n");
      out.write("\n");
      out.write("\t  actualizarVistaPrevia(idEvento);\n");
      out.write("\n");
      out.write("\n");
      out.write("  };\n");
      out.write("  function mostrarModalFacturas(idEvento){\n");
      out.write("\n");
      out.write("\t  $(\"#modalFacturas\").modal('show');\n");
      out.write("\n");
      out.write("\t  $.ajax({\n");
      out.write("\t\t\ttype:'POST',\n");
      out.write("\t\t\turl :\"/SAO/FacturaEventoSelectServlet\",\n");
      out.write("\t\t\tdata: {\n");
      out.write("\t\t\t\tID_EVENTO : idEvento\n");
      out.write("\t\t\t},\n");
      out.write("\t\t\tsuccess: function(data) {\n");
      out.write("\n");
      out.write("\t\t\t\t$(\"#divFacturas\").empty();\n");
      out.write("\t\t\t\t$(\"#divFacturas\").append(data);\n");
      out.write("\n");
      out.write("\t\t\t\t$(\"#divFacturas\").hide();\n");
      out.write("//\t \t\t\t$(\"#divInterpretesAsignados\").show();\n");
      out.write("\t\t\t\t$(\"#divFacturas\").show();\n");
      out.write("\t\t\t\t  $(\"#datatable-but\").DataTable({\n");
      out.write("\t\t                dom: \"Bfrtip\",\n");
      out.write("\n");
      out.write("\t\t                responsive: true\n");
      out.write("\t\t              });\n");
      out.write("\n");
      out.write("\t\t\t},\n");
      out.write("\t\t\terror:function(exception){console.log('Exeption:'+exception); /*logSystem*/ swal(  'Error',  'Proceso no completado',  'error');}\n");
      out.write("\t\t});\n");
      out.write("\n");
      out.write("\n");
      out.write("\t  };\n");
      out.write("\n");
      out.write("  function copiarMemoServicioEditores()\n");
      out.write("  {\n");
      out.write("\t var memoServicio = $(\"#divPrincipalMemo\").html();\n");
      out.write("\n");
      out.write("     $('#editorCliente').html(memoServicio);\n");
      out.write("     $('#editorOmni').html(memoServicio);\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  function obtenerMemoServicio(idEvento){\n");
      out.write("\t  //MemoServicioSelectServlet\n");
      out.write("\n");
      out.write("\t  $.ajax({\n");
      out.write("\t\t\ttype:'POST',\n");
      out.write("\t\t\turl :\"/SAO/MemoServicioSelectServlet\",\n");
      out.write("\t\t\tdata: {\n");
      out.write("\t\t\t\tID_EVENTO : idEvento\n");
      out.write("\t\t\t},\n");
      out.write("\t\t\tsuccess: function(data) {\n");
      out.write("\n");
      out.write("\t\t\t\t$(\"#divCapturaMemoEvento\").empty();\n");
      out.write("\t\t\t\t$(\"#divCapturaMemoEvento\").append(data);\n");
      out.write("\n");
      out.write("\t\t\t},\n");
      out.write("\t\t\terror:function(exception){console.log('Exeption:'+exception); /*logSystem*/ swal(  'Error',  'Proceso no completado',  'error');}\n");
      out.write("\t\t});\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  function actualizarVistaPrevia(idEvento) {\n");
      out.write("\n");
      out.write("\t\t$.ajax({\n");
      out.write("\t\t\ttype:'POST',\n");
      out.write("\t\t\turl :\"reporte_memo_servicio_html.jsp\",\n");
      out.write("\t\t\tdata: {\n");
      out.write("\t\t\t\tID_EVENTO : idEvento\n");
      out.write("\t\t\t},\n");
      out.write("\t\t\tsuccess: function(data) {\n");
      out.write("\n");
      out.write("\t\t\t\t$(\"#divVistaPrevia\").empty();\n");
      out.write("\t\t\t\t$(\"#divVistaPrevia\").append(data);\n");
      out.write("\n");
      out.write("\t\t\t\t//$(\"#divVistaPrevia\").hide();\n");
      out.write("\t\t\t\t//$(\"#divVistaPrevia\").show();\n");
      out.write("\t\t\t\tcopiarMemoServicioEditores();\n");
      out.write("\t\t\t},\n");
      out.write("\t\t\terror:function(exception){console.log('Exeption:'+exception); /*logSystem*/ swal(  'Error',  'Proceso no completado',  'error');}\n");
      out.write("\t\t});\n");
      out.write("\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t  function actualizarVistaPreviaEF(idEFactura) {\n");
      out.write("\n");
      out.write("\t\t\t$.ajax({\n");
      out.write("\t\t\t\ttype:'POST',\n");
      out.write("\t\t\t\turl :\"factura_html.jsp\",\n");
      out.write("\t\t\t\tdata: {\n");
      out.write("\t\t\t\t\tID_EVENTO: $(\"#auxIdEvento\").val(),\n");
      out.write("\t\t\t\t\tidFactura:idEFactura\n");
      out.write("\t\t\t\t},\n");
      out.write("\n");
      out.write("\t\t\t\t\tsuccess: function(data) {\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t$(\"#divVistaPreviaEF\").empty();\n");
      out.write("\t\t\t\t\t$(\"#divVistaPreviaEF\").append(data);\n");
      out.write("\n");
      out.write("\t\t\t\t\t//$(\"#divVistaPrevia\").hide();\n");
      out.write("\t\t\t\t\t//$(\"#divVistaPrevia\").show();\n");
      out.write("\t\t\t\t\tcopiarFacturaEditores();\n");
      out.write("\t\t\t\t},\n");
      out.write("\t\t\t\terror:function(exception){console.log('Exeption:'+exception); /*logSystem*/ swal(  'Error',  'Proceso no completado',  'error');}\n");
      out.write("\t\t\t});\n");
      out.write("\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\tfunction copiarFacturaEditores()\n");
      out.write("\t  {\n");
      out.write("\t\t var facturaHTML = $(\"#divVistaPreviaEF\").html();\n");
      out.write("\n");
      out.write("\t     $('#editorClienteEF').html(facturaHTML);\n");
      out.write("\t     $('#editorOmniEF').html(facturaHTML);\n");
      out.write("\t  }\n");
      out.write("\n");
      out.write("  \tfunction obtenerCorreoContactoCliente(idEvento, tipo_Correo){\n");
      out.write("  \t\t$.ajax({\n");
      out.write("\t\t\ttype:'POST',\n");
      out.write("\t\t\turl :\"/SAO/MemoServicioSelectedCorreoServlet\",\n");
      out.write("\t\t\tdata: {\n");
      out.write("\t\t\t\tID_EVENTO : idEvento,\n");
      out.write("\t\t\t\ttipoCorreo : tipo_Correo\n");
      out.write("\t\t\t},\n");
      out.write("\t\t\tsuccess: function(data) {\n");
      out.write("\n");
      out.write("\t\t\t\tif(tipo_Correo == '1'){\n");
      out.write("\t\t\t\t\t$(\"#txtCorreoCLiente\").empty();\n");
      out.write("  \t \t\t\t\t$(\"#txtCorreoCLiente\").val(data);\n");
      out.write("\t\t\t\t}else if(tipo_Correo == '3'){\n");
      out.write("\t\t\t\t\t$(\"#txtCorreoInterprete\").empty();\n");
      out.write("  \t \t\t\t\t$(\"#txtCorreoInterprete\").val(data);\n");
      out.write("\t\t\t\t} else\t{\n");
      out.write("\t\t\t\t\t\t$(\"#txtCorreoOmni\").empty();\n");
      out.write("  \t \t\t\t\t$(\"#txtCorreoOmni\").val(data);\n");
      out.write("\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t//$(\"#divVistaPrevia\").hide();\n");
      out.write("\t\t\t\t//$(\"#divVistaPrevia\").show();\n");
      out.write("\t\t\t\tcopiarMemoServicioEditores();\n");
      out.write("\t\t\t},\n");
      out.write("\t\t\terror:function(exception){console.log('Exeption:'+exception); /*logSystem*/ swal(  'Error',  'Proceso no completado',  'error');}\n");
      out.write("\t\t});\n");
      out.write("\n");
      out.write("\t}\n");
      out.write("  \tfunction actualizarCampoMemoServicio(component, id){\n");
      out.write("  \t\tvar v;\n");
      out.write("  \t\tif(component.type != 'checkbox'){\n");
      out.write("  \t\t\t v =  component.value;\n");
      out.write("  \t\t}else{\n");
      out.write("  \t\t\tv = $(component).prop(\"checked\")?1:0;\n");
      out.write("  \t\t}\n");
      out.write("  \t\t\n");
      out.write("  \t\t$.ajax({\n");
      out.write("  \t \t\ttype:'POST',\n");
      out.write("  \t \t\turl :\"/SAO/MemoServicioUpdateCampoServlet\",\n");
      out.write("  \t \t\tdata: {\n");
      out.write("  \t \t\t\tkey : id,\n");
      out.write("  \t \t\t\tcampo : component.id,\n");
      out.write("  \t\t\t\tvalor : v\n");
      out.write("  \t \t\t},\n");
      out.write("  \t \t\tsuccess: function(data) {\n");
      out.write("\n");
      out.write("  \t \t\t\t//$(\"#divSedes\").hide();\n");
      out.write("  \t \t\t\t//$(\"#divSedes\").toggle(200);\n");
      out.write("  \t \t\t\tactualizarVistaPrevia(idEventoGlobal);\n");
      out.write("\n");
      out.write("  \t \t\t},\n");
      out.write("  \t \t\terror:function(exception){console.log('Exeption:'+exception); /*logSystem*/ swal(  'Error',  'Proceso no completado',  'error');}\n");
      out.write("  \t \t});\n");
      out.write("  \t}\n");
      out.write("\n");
      out.write("  \tfunction obtenerNombreEvento(idEvento){\n");
      out.write("  \t\t//\n");
      out.write("  \t\t$.ajax({\n");
      out.write("  \t \t\ttype:'POST',\n");
      out.write("  \t \t\turl :\"/SAO/MemoServicioSelectedNombreEventoServlet\",\n");
      out.write("  \t \t\tdata: {\n");
      out.write("  \t \t\t\tID_EVENTO: idEvento\n");
      out.write("  \t \t\t},\n");
      out.write("  \t \t\tsuccess: function(data) {\n");
      out.write("  \t \t\t\tvar asunto = \"Memo de servicio: \";\n");
      out.write("  \t \t\t\t$(\"#txtAsuntoCLiente\").empty();\n");
      out.write("\t \t\t\t$(\"#txtAsuntoCLiente\").val(asunto + data);\n");
      out.write("\n");
      out.write("  \t \t\t\t$(\"#txtAsuntoOmni\").empty();\n");
      out.write("\t \t\t\t$(\"#txtAsuntoOmni\").val(asunto + data);\n");
      out.write("\n");
      out.write("  \t \t\t},\n");
      out.write("  \t \t\terror:function(exception){console.log('Exeption:'+exception); /*logSystem*/ swal(  'Error',  'Proceso no completado',  'error');}\n");
      out.write("  \t \t});\n");
      out.write("  \t}\n");
      out.write("\n");
      out.write("\n");
      out.write("  \tvar funcEnviarCorreoMemo = function (){\n");
      out.write("  \t\t$.ajax({\n");
      out.write("  \t \t\ttype:'POST',\n");
      out.write("  \t \t\turl :\"/SAO/NotificacionMemoServicioServlet\",\n");
      out.write("  \t \t\tdata: {\n");
      out.write("  \t \t\t\tid_evento : idEventoGlobal,\n");
      out.write("  \t \t\t\temailCliente: $(\"#txtCorreoCLiente\").val(),\n");
      out.write("  \t \t\t\temailOmnilingua: $(\"#txtCorreoOmni\").val(),\n");
      out.write("\t\t\t\t\temailIntepretes: $(\"#txtCorreoInterprete\").val(),\n");
      out.write("  \t \t\t\tasuntoCliente : $(\"#txtAsuntoCLiente\").val(),\n");
      out.write("  \t \t\t\tasuntoOmnilingua : $(\"#txtAsuntoOmni\").val(),\n");
      out.write("  \t \t\t\tmensajeCliente : $(\"#editorCliente\").html(),\n");
      out.write("  \t \t\t\tmensajeOmnilingua : $(\"#editorOmni\").html()\n");
      out.write("  \t \t\t},\n");
      out.write("  \t \t\tsuccess: function(data) {\n");
      out.write("\n");
      out.write("  \t\t \t\tif(data == \"OK\")\n");
      out.write("  \t\t \t\t{\n");
      out.write("  \t\t \t\t\tswal('Memo de Servicio enviado');\n");
      out.write("\t\t\t\t\t\t$(\"#modalMemoServicio\").modal('hide');\n");
      out.write("  \t\t \t\t}\n");
      out.write("  \t \t\t},\n");
      out.write("  \t \t\terror:function(exception){console.log('Exeption:'+exception); /*logSystem*/ swal(  'Error',  'Proceso no completado',  'error');}\n");
      out.write("  \t \t});\n");
      out.write("  \t};\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\tvar funcEnviarCorreoFactura = function (){\n");
      out.write("\t\t\t$.ajax({\n");
      out.write("\t\t\t\ttype:'POST',\n");
      out.write("\t\t\t\turl :\"/SAO/NotificacionFacturaServlet\",\n");
      out.write("\t\t\t\tdata: {\n");
      out.write("\t\t\t\t\tid_factura : idDetalleGlobal,\n");
      out.write("\t\t\t\t\tid_evento : idEventoGlobal,\n");
      out.write("\t\t\t\t\temailOmnilingua: $(\"#txtCorreoOmniEF\").val(),\n");
      out.write("\t\t\t\t\tasuntoOmnilingua : $(\"#txtAsuntoOmniEF\").val(),\n");
      out.write("\t\t\t\t\tmensajeOmnilingua : $(\"#editorOmniEF\").html()\n");
      out.write("\t\t\t\t},\n");
      out.write("\t\t\t\tsuccess: function(data) {\n");
      out.write("\n");
      out.write("\t\t\t\t\tif(data == \"OK\")\n");
      out.write("\t\t\t\t\t{\n");
      out.write("\t\t\t\t\t\tswal('Detalle de factura enviado');\n");
      out.write("\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t},\n");
      out.write("\t\t\t\terror:function(exception){console.log('Exeption:'+exception); /*logSystem*/ swal(  'Error',  'Proceso no completado',  'error');}\n");
      out.write("\t\t\t});\n");
      out.write("\t\t};\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\t<script src=\"../home/vendors/sweet_alert/sweetalert.min.js\"></script>\n");
      out.write("\t<script src=\"../home/vendors/jquery.hotkeys/jquery.hotkeys.js\"></script>\n");
      out.write("\t<script src=\"../home/vendors/DateJS/prettify.js\"></script>\n");
      out.write("\t<script src=\"../home/vendors/bootstrap-wysiwyg/src/bootstrap-wysiwyg.js\"></script>\n");
      out.write("\n");
      out.write("\t<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("\t\t");
 if(message != null && !message.equals("")) { 
      out.write("\n");
      out.write("\t\tswal(\"Mensaje:\", \"");
      out.print( message );
      out.write("\", \"success\");\n");
      out.write("\t\t");
 }
      out.write("\n");
      out.write("\n");
      out.write("\t</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    <!-- Datatables -->\n");
      out.write("    <script>\n");
      out.write("\n");
      out.write("    $(document).ready(function() {\n");
      out.write("        var handleDataTableButtons = function() {\n");
      out.write("          if ($(\"#datatable-buttons\").length) {\n");
      out.write("            $(\"#datatable-buttons\").DataTable({\n");
      out.write("              dom: \"Bfrtip\",\n");
      out.write("              buttons: [\n");
      out.write("            \t  {\n");
      out.write("                      extend: \"copy\",\n");
      out.write("                      className: \"btn-sm\",\n");
      out.write("                      text : \"Copiar\"\n");
      out.write("                    },\n");
      out.write("                    {\n");
      out.write("                      extend: \"csv\",\n");
      out.write("                      className: \"btn-sm\",\n");
      out.write("                      text : \"Descargar CSV\"\n");
      out.write("                    },\n");
      out.write("                    {\n");
      out.write("                      extend: \"excel\",\n");
      out.write("                      className: \"btn-sm\",\n");
      out.write("                      text : \"Descargar Excel\"\n");
      out.write("                    },\n");
      out.write("                    {\n");
      out.write("                      extend: \"pdfHtml5\",\n");
      out.write("                      className: \"btn-sm\"\n");
      out.write("                    }\n");
      out.write("                    /*,\n");
      out.write("                    {\n");
      out.write("                      extend: \"print\",\n");
      out.write("                      className: \"btn-sm\"\n");
      out.write("                    },*/\n");
      out.write("              ],\n");
      out.write("              responsive: true\n");
      out.write("            });\n");
      out.write("          }\n");
      out.write("        };\n");
      out.write("\n");
      out.write("        TableManageButtons = function() {\n");
      out.write("          \"use strict\";\n");
      out.write("          return {\n");
      out.write("            init: function() {\n");
      out.write("              handleDataTableButtons();\n");
      out.write("            }\n");
      out.write("          };\n");
      out.write("        }();\n");
      out.write("\n");
      out.write("        $('#datatable').dataTable();\n");
      out.write("\n");
      out.write("        $('#datatable-keytable').DataTable({\n");
      out.write("          keys: true\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        $('#datatable-responsive').DataTable();\n");
      out.write("\n");
      out.write("        $('#datatable-scroller').DataTable({\n");
      out.write("          ajax: \"js/datatables/json/scroller-demo.json\",\n");
      out.write("          deferRender: true,\n");
      out.write("          scrollY: 380,\n");
      out.write("          scrollCollapse: true,\n");
      out.write("          scroller: true\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        $('#datatable-fixed-header').DataTable({\n");
      out.write("          fixedHeader: true\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        var $datatable = $('#datatable-checkbox');\n");
      out.write("\n");
      out.write("        $datatable.dataTable({\n");
      out.write("          'order': [[ 1, 'asc' ]],\n");
      out.write("          'columnDefs': [\n");
      out.write("            { orderable: false, targets: [0] }\n");
      out.write("          ]\n");
      out.write("        });\n");
      out.write("        $datatable.on('draw.dt', function() {\n");
      out.write("          $('input').iCheck({\n");
      out.write("            checkboxClass: 'icheckbox_flat-green'\n");
      out.write("          });\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        TableManageButtons.init();\n");
      out.write("\n");
      out.write("        $('#editorCliente').wysiwyg();\n");
      out.write("        $('#editorOmni').wysiwyg();\n");
      out.write("\n");
      out.write("      });\n");
      out.write("\n");
      out.write("\n");
      out.write("    </script>\n");
      out.write("    <!-- /Datatables -->\n");
      out.write("  </body>\n");
      out.write("</html>\n");

    } else {
    	response.sendRedirect("../home/login.jsp");
    }
}catch(Exception _e){
	System.out.println("Error"+_e);
	_e.printStackTrace();
}

      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
