/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.82
 * Generated at: 2018-06-05 23:46:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.home;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.movemini.config.HardCodeConstants;
import com.movemini.layers.controller.login.LoginControllerBean;
import java.sql.*;
import java.io.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


	response.setHeader("Cache-Control","no-cache"); //HTTP 1.1
	response.setHeader("Pragma","no-cache"); //HTTP 1.0
	response.setDateHeader ("Expires", 0); //prevents caching at the proxy server

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write(" \n");
      out.write(" \n");
      out.write("<!DOCTYPE html>\n");
      out.write("\t<html lang=\"en\">\n");
      out.write("\t<head>\n");
      out.write("\t\t<meta charset=\"UTF-8\">\n");
      out.write("\t\t<title>");
      out.print( HardCodeConstants.CONTEXT_PATH );
      out.write("</title>\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("\n");
      out.write("\t\t<!-- google fonts -->\n");
      out.write("\n");
      out.write("\t\t<!-- Css link -->\n");
      out.write("\n");
      out.write("<!-- \t\t<link rel=\"stylesheet\" href=\"http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css\"> -->\n");
      out.write("<!-- \t\t<link rel=\"stylesheet\" href=\"loginFiles/font-awesome.min.css\"> -->\n");
      out.write("<!-- \t\t<link rel=\"stylesheet\" href=\"loginFiles/owl.carousel.css\"> -->\n");
      out.write("<!-- \t\t<link rel=\"stylesheet\" href=\"loginFiles/owl.transitions.css\"> -->\n");
      out.write("<!-- \t\t<link rel=\"stylesheet\" href=\"loginFiles/animate.min.css\"> -->\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"loginFiles/lightbox.css\">\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"loginFiles/bootstrap.min.css\">\n");
      out.write("<!-- \t\t<link rel=\"stylesheet\" href=\"loginFiles/preloader.css\"> -->\n");
      out.write("<!-- \t\t<link rel=\"stylesheet\" href=\"loginFiles/image.css\"> -->\n");
      out.write("<!-- \t\t<link rel=\"stylesheet\" href=\"loginFiles/icon.css\"> -->\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"loginFiles/style.css\">\n");
      out.write("<!-- \t\t<link rel=\"stylesheet\" href=\"loginFiles/responsive.css\"> -->\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"vendors/sweet_alert/sweetalert.css\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\t</head>\n");
      out.write("\t<body id=\"top\">\n");
      out.write("\n");
      out.write("\n");
      out.write("        <header id=\"navigation\" class=\"navbar-fixed-top animated-header\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"navbar-header\">\n");
      out.write("                    <!-- responsive nav button -->\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">\n");
      out.write("\t\t\t\t\t\t<span class=\"sr-only\">Toggle navigation</span>\n");
      out.write("\t\t\t\t\t\t<span class=\"icon-bar\"></span>\n");
      out.write("\t\t\t\t\t\t<span class=\"icon-bar\"></span>\n");
      out.write("\t\t\t\t\t\t<span class=\"icon-bar\"></span>\n");
      out.write("                    </button>\n");
      out.write("\t\t\t\t\t<!-- /responsive nav button -->\n");
      out.write("\n");
      out.write("\t\t\t\t\t<!-- logo -->\n");
      out.write("\t\t\t\t\t<h1 class=\"navbar-brand\">\n");
      out.write("\t\t\t\t\t\t<a href=\"#body\">\n");
      out.write("\t\t\t\t\t\t\t<!--\n");
      out.write("\t\t\t\t\t\t\t<img src=\"img/logo.png\" height=\"40\" width=\"164\" alt=\"\">\n");
      out.write("\t\t\t\t\t\t\t-->\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../img/Logo-Omnilingua-Smaller.png\" alt=\"\">\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t</h1>\n");
      out.write("\t\t\t\t\t<!-- /logo -->\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- main nav -->\n");
      out.write("                <nav class=\"collapse navbar-collapse navbar-right\" role=\"navigation\">\n");
      out.write("                    <ul id=\"nav\" class=\"nav navbar-nav menu\">\n");
      out.write("                                        \n");
      out.write("                        <li><a href=\"http://omnilingua.com.mx//\">Omnilingua.com.mx</a></li>\n");
      out.write("                        \n");
      out.write("                        <li><a href=\"/");
      out.print( HardCodeConstants.CONTEXT_PATH );
      out.write("/doc/Manual_de_Usuario_SAO.pdf\" target=\"_blank\">Manual de Usuario de SAO</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                </nav>\n");
      out.write("\t\t\t\t<!-- /main nav -->\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </header>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<div class=\"wrapper\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t<section id=\"banner\">\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t<div class=\"row\">\n");
      out.write("<!-- \t\t\t\t\t class=\"col-md-6\" -->\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6\">\n");
      out.write("\t\t\t\t\t\t<div class=\"block\">\n");
      out.write("\t\t\t\t\t\t\t<br>\n");
      out.write("\t\t\t\t\t\t\t<h1>\n");
      out.write("\t\t\t\t\t\t\t\t\t<!--Clean and Flexible Business Template-->\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tSAO\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</h1>\n");
      out.write("\t\t\t\t\t\t\t<span class=\"smallerH1\">Sistema Automatizado Omnilingua</span>\n");
      out.write("\t\t\t\t\t\t\t<p>&nbsp;</p>\n");
      out.write("\t\t\t\t\t\t\t<p>&nbsp;</p>\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t<h2>\n");
      out.write("\t\t\t\t\t\t\t\t\t<!--\n");
      out.write("\t\t\t\t\t\t\t\t\tLorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod <br> tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,-->\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\tIngrese sus datos para acceder al sistema:\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</h2>\n");
      out.write("<!-- \t\t\t\t\t\t\t<BR> -->\n");
      out.write("<!-- \t\t\t\t\t\t\t\t<BR> -->\n");
      out.write("\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t<div class=\"buttons\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<form method=\"post\" action=\"login.jsp\" name=\"login\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" autofocus name=\"user\" class=\"form-control\" placeholder=\"Usuario\" required=\"required\" width=\"80%\" tabindex=\"1\" />\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<BR>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"password\" name=\"pass\" class=\"form-control\" placeholder=\"Contraseña\" required=\"required\" tabindex=\"2\" />\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<BR>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div align='right'>\n");
      out.write("<!-- \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-learn\">Ingresar</a> -->\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<button type=\"submit\" style=\"float: right;\" class=\"btn btn-default submit\" tabindex=\"3\" name=\"login\">Ingresar</button>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t\t\t\t<!--\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-learn\">Purchase Now</a>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-learn\">View Featurese</a>\n");
      out.write("\t\t\t\t\t\t\t\t-->\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- \t\t\t\t\t</div> -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"scrolldown\">\n");
      out.write("\t\t\t\t<!--\n");
      out.write("\t            <a id=\"scroll\" href=\"#features\" class=\"scroll\"></a>\n");
      out.write("\t        -->\n");
      out.write("\t        </div>\n");
      out.write("\t\t</section>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t<footer>\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t<div class=\"row\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"col-md-12\">\n");
      out.write("\t\t\t\t\t\t<div class=\"block\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<!--<a href=\"#\"><img src=\"img/logo.png\" alt=\"\"></a>-->\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<p>© Omnilingua. Todos los derechos reservados. 2017</p>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</footer>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t\t<!-- load Js -->\n");
      out.write("\t\t<script src=\"loginFiles/jquery-1.11.3.min.js\"></script>\n");
      out.write("\t\t<script src=\"loginFiles/bootstrap.min.js\"></script>\n");
      out.write("<!-- \t\t<script src=\"loginFiles/waypoints.min.js\"></script> -->\n");
      out.write("<!-- \t\t<script src=\"loginFiles/lightbox.js\"></script> -->\n");
      out.write("<!-- \t\t<script src=\"loginFiles/jquery.counterup.min.js\"></script> -->\n");
      out.write("<!-- \t\t<script src=\"loginFiles/owl.carousel.min.js\"></script> -->\n");
      out.write("<!-- \t\t<script src=\"loginFiles/html5lightbox.js\"></script> -->\n");
      out.write("<!-- \t\t<script src=\"loginFiles/jquery.mixitup.js\"></script> -->\n");
      out.write("<!-- \t\t<script src=\"loginFiles/wow.min.js\"></script> -->\n");
      out.write("<!-- \t\t<script src=\"loginFiles/jquery.scrollUp.js\"></script> -->\n");
      out.write("<!-- \t\t<script src=\"loginFiles/jquery.sticky.js\"></script> -->\n");
      out.write("\t\t<script src=\"loginFiles/jquery.nav.js\"></script>\n");
      out.write("<!-- \t\t<script src=\"loginFiles/main.js\"></script> -->\n");
      out.write("\t\t<script src=\"vendors/sweet_alert/sweetalert.min.js\"></script>\n");
      out.write("\t\t\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t");

				try{
					LoginControllerBean bean = new LoginControllerBean(request);
	
	
				    String user = request.getParameter("user");
				    String pass = request.getParameter("pass");
				    
				    
				    if(request.getParameter("login") != null){
				    	
				    	String result = bean.doLogin(user, pass);
				    	
				    	out.print(result);
				    }
				}catch(IllegalArgumentException iaex){
					
				
      out.write("\n");
      out.write("\t\t\t\t\t\t<script>    \t\t\t\n");
      out.write("\t\t\t\t    \t\t\n");
      out.write("// \t\t\t\t\t\t\tsetTimeout(function() {\n");
      out.write("// \t\t\t\t    \t\t    $('#mydiv').fadeOut('fast');\n");
      out.write("// \t\t\t\t    \t\t}, 4000);\n");
      out.write("\t\t\t    \t\t\n");
      out.write("\t\t\t\t    \t\t//alert(\"");
      out.print( iaex.getMessage() );
      out.write("\");\n");
      out.write("\t\t\t\t    \t\tswal({title:\"\",text: \"");
      out.print( iaex.getMessage() );
      out.write("\",type: \"info\", html:true});\n");
      out.write("\t\t\t\t    \t\t\n");
      out.write("\t\t\t    \t\t</script>\n");
      out.write("\t\t\t    \t\t\n");
      out.write("\t\t\t    \t\t \n");
      out.write("<!-- \t\t\t    \t\t<center> -->\n");
      out.write("<!-- \t\t\t    \t\t style=\"padding-left: 300px; padding-right: 500px;\" -->\n");
      out.write("<!-- \t\t\t\t    \t\t<div> -->\n");
      out.write("<!-- \t\t\t\t\t    \t\t<div class=\"alert alert-info\" id=\"mydiv\" style=\"padding-left: 40px; padding-right: 40px;\">\t\t    \t\t -->\n");
      out.write("\t\t\t\t\t\t\t    \t\n");
      out.write("<!-- \t\t\t\t\t\t\t    </div> -->\n");
      out.write("<!-- \t\t\t\t    \t\t</div> -->\n");
      out.write("<!-- \t\t\t    \t\t</center> -->\n");
      out.write("\t\t\t\t");

					//out.println();
				
				}catch(Exception ex){
					System.out.println(ex);
					ex.printStackTrace();
				}
				
			
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
