/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.82
 * Generated at: 2018-06-05 23:46:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.home;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.apache.tomcat.util.codec.binary.Base64;
import java.sql.*;
import java.io.*;
import java.util.List;
import java.util.ArrayList;
import com.movemini.config.HardCodeConstants;
import com.movemini.layers.session.SessionBean;
import com.movemini.layers.view.menu.RecordCounter;
import com.movemini.data.DataArray;
import com.movemini.data.Record;
import com.movemini.data.ConnectionWrapper;
import java.sql.DriverManager;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import java.sql.ResultSet;
import java.sql.Statement;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/home/commonSideBarMenu.jsp", Long.valueOf(1527701485317L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


	response.setHeader("Cache-Control","no-cache"); //HTTP 1.1
	response.setHeader("Pragma","no-cache"); //HTTP 1.0
	response.setDateHeader ("Expires", 0); //prevents caching at the proxy server

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write(" \n");
      out.write(" \n");
      out.write("\n");
      out.write(" \n");
      out.write("\n");

try
{
// 	Class.forName("com.mysql.jdbc.Driver");
//     String url="jdbc:mysql://localhost:3306/prosante";
//     String username="root";
//     String password="120315";
//     Connection conn=DriverManager.getConnection(url,username,password);
    
//     if(session.getAttribute("ID_USER") != null) {
// 	    List<String> lstMenuPadres = new ArrayList<String>();
// 	    String Role = "";
//     	Statement stScreen = conn.createStatement();
//     	ResultSet rsScreen = stScreen.executeQuery("SELECT * FROM screen_role WHERE ID_ROLE = '"+session.getAttribute("ID_ROLE")+"'");
//     	while(rsScreen.next()){
//     		Statement stName = conn.createStatement();
// 	    	ResultSet rsName = stName.executeQuery("SELECT * FROM menu WHERE ID_SCREEN = '"+rsScreen.getInt(1)+"' and ID_PADRE = 0 AND ID_ROLE ="+session.getAttribute("ID_ROLE")+" ORDER BY ID_ORDER, ID");
// 	    	while(rsName.next()){
// 	    		lstMenuPadres.add(rsName.getString("NAME"));	    	
// 	    	}
// 	    }
	    		       	
//     	Statement stR = conn.createStatement();
//     	ResultSet rsR = stR.executeQuery("SELECT * FROM role WHERE ID = "+session.getAttribute("ID_ROLE")+"");
//     	while(rsR.next()){
//     		Role = rsR.getString(2);
//     	}
    	
//     	String[] dtaUser = new String[10];
//     	String imagen = "";    	    	
    	
//     	Statement stUs = conn.createStatement();
//     	ResultSet rsUs = stUs.executeQuery("SELECT * FROM user WHERE ID = "+session.getAttribute("ID_USER")+"");
//     	while(rsUs.next()){
//     		dtaUser[0] = rsUs.getString(1);
//     		dtaUser[1] = rsUs.getString(2);
//     		dtaUser[2] = rsUs.getString(3);
//     		dtaUser[3] = rsUs.getString(4);
//     		dtaUser[4] = rsUs.getString(5);
//     		dtaUser[5] = rsUs.getString(6);
//     		dtaUser[6] = rsUs.getString(7);
//     		dtaUser[7] = rsUs.getString(8);
//     		if(rsUs.getString(9) != null){    	
//     			imagen = rsUs.getString(9);
//     		}
//     		else{
//     			Statement stDef = conn.createStatement();
//     			ResultSet rsDef = stDef.executeQuery("SELECT * FROM configuracion WHERE id_conf = 3");
//     			while(rsDef.next()){	    			
// 					imagen = rsDef.getString(3);
//     			}
//     		}
//     		dtaUser[9] = rsUs.getString(10);
//     	}    	      	    	
		    	

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html lang=\"en\">\n");
      out.write("  <head>\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("    <!-- Meta, title, CSS, favicons, etc. -->\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("\n");
      out.write("    <title>SAO </title>\n");
      out.write("\n");
      out.write("    <!-- Bootstrap -->\n");
      out.write("    <link href=\"vendors/bootstrap/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <!-- Font Awesome -->\n");
      out.write("    <link href=\"vendors/font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\">\n");
      out.write("    <!-- NProgress -->\n");
      out.write("    <link href=\"vendors/nprogress/nprogress.css\" rel=\"stylesheet\">\n");
      out.write("    <!-- iCheck -->\n");
      out.write("    ");
      out.write("\n");
      out.write("    <!-- bootstrap-progressbar -->\n");
      out.write("    <link href=\"vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css\" rel=\"stylesheet\">\n");
      out.write("    <!-- JQVMap -->\n");
      out.write("    <link href=\"vendors/jqvmap/dist/jqvmap.min.css\" rel=\"stylesheet\"/>\n");
      out.write("\n");
      out.write("    <!-- Custom Theme Style -->\n");
      out.write("    <link href=\"build/css/custom.css\" rel=\"stylesheet\">\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    \n");
      out.write("  </head>\n");
      out.write("  <body class=\"nav-md\">\n");
      out.write("    <div class=\"container body\">\n");
      out.write("      <div class=\"main_container\">\n");
      out.write("      \n");
      out.write("      \n");
      out.write("      \t");
      out.write('\n');
      out.write('\n');

	response.setHeader("Cache-Control","no-cache"); //HTTP 1.1
	response.setHeader("Pragma","no-cache"); //HTTP 1.0
	response.setDateHeader ("Expires", 0); //prevents caching at the proxy server

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");




// 	Connection connx = ConnectionWrapper.getDirectJDBCConnection();



Record user = SessionBean.getInstance(request).getUser();



// 	List<String> lstMenuPadres = new ArrayList<String>();
// 	String Role = "";

// 	Statement stScreen = connx.createStatement();
// 	ResultSet rsScreen = stScreen.executeQuery("SELECT * FROM screen_role WHERE ID_ROLE = '"+session.getAttribute("ID_ROLE")+"'");
// 	while(rsScreen.next()){
// 		Statement stName = connx.createStatement();
// 		ResultSet rsName = stName.executeQuery("SELECT * FROM menu WHERE ID_SCREEN = '"+rsScreen.getInt(1)+"' and ID_PADRE = 0 AND ID_ROLE ="+session.getAttribute("ID_ROLE")+" ORDER BY ID_ORDER, ID");
// 		while(rsName.next()){
// 			lstMenuPadres.add(rsName.getString("NAME"));
// 		}
// 	}



	ArrayList<Record> menuParents = DataArray.getArrayList("SELECT * FROM ss_menu WHERE id_menu_padre = 0 AND accesos LIKE '%" + user.get("id_rol") + "%' ORDER BY id_orden");




// 	Statement stR = connx.createStatement();
// 	ResultSet rsR = stR.executeQuery("SELECT * FROM role WHERE ID = "+session.getAttribute("ID_ROLE")+"");
// 	while(rsR.next()){
// 		Role = rsR.getString(2);
// 	}




// 	String[] dtaUser = new String[10];
// 	String imagen = "";
// 	String imagenUser = "";
// 	Statement stUs = connx.createStatement();
// 	//ResultSet rsUs = stUs.executeQuery("SELECT * FROM user WHERE ID = "+session.getAttribute("ID_USER")+"");
// 	while(rsUs.next()){
// // 		dtaUser[0] = rsUs.getString(1);
// // 		dtaUser[1] = rsUs.getString(2);
// // 		dtaUser[2] = rsUs.getString(3);
// // 		dtaUser[3] = rsUs.getString(4);
// // 		dtaUser[4] = rsUs.getString(5);
// // 		dtaUser[5] = rsUs.getString(6);
// // 		dtaUser[6] = rsUs.getString(7);
// // 		dtaUser[7] = rsUs.getString(8);
// 		if(rsUs.getString(9)!= null){
// 			imagen = rsUs.getString(9);
// 		}
// 		else{
// 			Statement stDef = connx.createStatement();
// 			ResultSet rsDef = stDef.executeQuery("SELECT * FROM configuracion WHERE id_conf = 3");
// 			while(rsDef.next()){
// 				imagen = rsDef.getString(3);
// 			}
// 		}
// 		dtaUser[9] = rsUs.getString(10);
// 	}




// 	Statement stEditEvento = connx.createStatement();
// 	ResultSet rsEditEvento = stEditEvento.executeQuery("SELECT * FROM evento WHERE ID = "+request.getParameter("ID_EVENTO")+"");
// 	String[] lstEvento = new String[12];
// 	while(rsEditEvento.next()){
// 		lstEvento[0] =  rsEditEvento.getString(1);
// 		lstEvento[1] =  rsEditEvento.getString(2);
// 		lstEvento[2] =  rsEditEvento.getString(3);
// 		lstEvento[3] =  rsEditEvento.getString(4);
// 		lstEvento[4] =  rsEditEvento.getString(5);
// 		lstEvento[5] =  rsEditEvento.getString(6);
// 		lstEvento[6] =  rsEditEvento.getString(7);
// 	}










      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("      <div class=\"col-md-3 left_col\">\n");
      out.write("          <div class=\"left_col scroll-view\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t \t\t<div class=\"navbar nav_title\" style=\"border: 0;\">\n");
      out.write("\t\t              <a href=\"main.jsp\" class=\"site_title\"> <span>SAO</span></a>\n");
      out.write("\t\t            </div>\n");
      out.write("\t\t            <div class=\"clearfix\"></div>\n");
      out.write("\n");
      out.write("\t\t           <!--\n");
      out.write("\t\t            -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t            <!-- menu profile quick info -->\n");
      out.write("\t\t            <div class=\"profile\">\n");
      out.write("\t\t              <div class=\"profile_pic\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t              <img id='profileImg1' src=\"/");
      out.print( HardCodeConstants.CONTEXT_PATH );
      out.write("/ProfilePhotoServlet\" width=\"40%\" height=\"40%\" class=\"img-circle profile_img\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t              </div>\n");
      out.write("\t\t              <div class=\"profile_info\">\n");
      out.write("\t\t                <!--<span>");
      out.print( user.get("rol_name") );
      out.write("</span>-->\n");
      out.write("\t\t                <h2>");
      out.print( user.get("nombre") );
      out.print(" ");
      out.print( user.get("apellido") );
      out.write("</h2>\n");
      out.write("\t\t              </div>\n");
      out.write("\t\t            </div>\n");
      out.write("\t\t            <!-- /menu profile quick info -->\n");
      out.write("\n");
      out.write("\t\t            <br />\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t<!-- sidebar menu -->\n");
      out.write("\t\t            <div id=\"sidebar-menu\" class=\"main_menu_side hidden-print main_menu\">\n");
      out.write("\t\t              <div class=\"menu_section\">\n");
      out.write("\t\t                <!-- <h3>Menu</h3>-->\n");
      out.write("\t\t                <br>\n");
      out.write("\t\t                <br>\n");
      out.write("\t\t                <br>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t                <ul class=\"nav side-menu\">\n");
      out.write("\t\t                ");




		                for (Record recordParent: menuParents) {

		                	//Statement st1 = connx.createStatement();
		                    //ResultSet rs1 = st1.executeQuery("SELECT * FROM menu m WHERE m.NAME = '"+item+"' AND ID_ROLE = "+session.getAttribute("ID_ROLE")+" ORDER BY ID_ORDER, ID");

		                    
      out.write("\n");
      out.write("\t\t                \t<li><a>\n");
      out.write("\t\t                \t\t\t<i class=\"");
      out.print(recordParent.getString("class") );
      out.write("\"></i>\n");
      out.write("\t\t                \t\t\t\t\t");
      out.print(recordParent.get("nombre") );
      out.write("\n");
      out.write("\t\t                \t\t\t\t\t<span class=\"fa fa-chevron-down\"></span>\n");
      out.write("\t\t                \t\t</a>\n");
      out.write("\t\t                \t\t<ul class=\"nav child_menu\">\n");
      out.write("\t\t                \t\t");





		                	ArrayList<Record> menuChilds = DataArray.getArrayList("SELECT * FROM ss_menu WHERE id_menu_padre = " + recordParent.get("id_menu") + " AND accesos LIKE '%" + user.get("id_rol") + "%' ORDER BY id_orden");

		                	for (Record recordChild: menuChilds) {
		                    	
      out.write("\n");
      out.write("\n");
      out.write("\t\t                \t\t\t<li class=\"");
      out.print(recordChild.getString("class") );
      out.write("\"><a href=\"");
      out.print(recordChild.getString("url"));
      out.write("\">\n");
      out.write("\t\t                \t\t\t");
      out.print( recordChild.getString("nombre") );
      out.write("\n");
      out.write("\t\t                \t\t\t");
      out.print( RecordCounter.getCount(user.get("id_usuario"), recordChild.get("url")) );
      out.write("\n");
      out.write("\t\t                \t\t\t</a></li>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t                \t\t\t");

		                    }

		                    
      out.write("\n");
      out.write("\t\t                    \t</ul>\n");
      out.write("\t\t                   \t</li>\n");
      out.write("\t\t                    ");

		                }
		                
      out.write("\n");
      out.write("\t\t                </ul>\n");
      out.write("\t\t              </div>\n");
      out.write("\t\t            </div>\n");
      out.write("\t\t            <!-- /sidebar menu -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t            <!-- /menu footer buttons -->\n");
      out.write("\t\t            <div class=\"sidebar-footer hidden-small\">\n");
      out.write("\t\t            <!--\n");
      out.write("\t\t              <a data-toggle=\"tooltip\" data-placement=\"top\" title=\"Settings\">\n");
      out.write("\t\t                <span class=\"glyphicon glyphicon-cog\" aria-hidden=\"true\"></span>\n");
      out.write("\t\t              </a>\n");
      out.write("\t\t              <a data-toggle=\"tooltip\" data-placement=\"top\" title=\"FullScreen\">\n");
      out.write("\t\t                <span class=\"glyphicon glyphicon-fullscreen\" aria-hidden=\"true\"></span>\n");
      out.write("\t\t              </a>\n");
      out.write("\t\t              <a data-toggle=\"tooltip\" data-placement=\"top\" title=\"Lock\">\n");
      out.write("\t\t                <span class=\"glyphicon glyphicon-eye-close\" aria-hidden=\"true\"></span>\n");
      out.write("\t\t              </a>\n");
      out.write("\t\t               -->\n");
      out.write("\t\t              <a data-toggle=\"tooltip\" data-placement=\"top\" title=\"Logout\" href=\"../home/logOut.jsp\">\n");
      out.write("\t\t                <span class=\"glyphicon glyphicon-off\" aria-hidden=\"true\"></span>\n");
      out.write("\t\t              </a>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<!--\t<a href=\"javascript:void(0);\" data-toggle=\"tooltip\" onclick=\"alert()\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"glyphicon glyphicon-bell\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"badge bg-green\">6</span>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t</a> -->\n");
      out.write("\n");
      out.write("\t\t            </div>\n");
      out.write("\t\t            <!-- /menu footer buttons -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("        <!-- top navigation -->\n");
      out.write("        <div class=\"top_nav\">\n");
      out.write("          <div class=\"nav_menu\">\n");
      out.write("            <nav>\n");
      out.write("              <div class=\"nav toggle\">\n");
      out.write("                <a id=\"menu_toggle\"><i class=\"fa fa-bars\"></i></a>\n");
      out.write("              </div>\n");
      out.write("\n");
      out.write("              <ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("                <li class=\"\">\n");
      out.write("                  <a href=\"javascript:;\" class=\"user-profile dropdown-toggle\" data-toggle=\"dropdown\" aria-expanded=\"false\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                    <img id='profileImg2' src=\"/");
      out.print( HardCodeConstants.CONTEXT_PATH );
      out.write("/ProfilePhotoServlet\" width=\"40%\" height=\"40%\">\n");
      out.write("\n");
      out.write("                    ");
      out.print( user.get("nombre") );
      out.print(" ");
      out.print( user.get("apellido") );
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                    <span class=\" fa fa-angle-down\"></span>\n");
      out.write("                  </a>\n");
      out.write("                  <ul class=\"dropdown-menu dropdown-usermenu pull-right\">\n");
      out.write("                    <li><a href=\"../home/logOut.jsp\"><i class=\"fa fa-sign-out pull-right\"></i>Salir </a></li>\n");
      out.write("\n");
      out.write("                  </ul>\n");
      out.write("                </li>\n");
      out.write("\n");
      out.write("              </ul>\n");
      out.write("            </nav>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- /top navigation -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");



// ConnectionWrapper.closeAll(rsScreen, stScreen, rsR, stR, connx);



      out.write('\n');
      out.write("\n");
      out.write("      \t\n");
      out.write("      \t\n");
      out.write("\n");
      out.write("        <!-- page content -->\n");
      out.write("        <div class=\"right_col\" role=\"main\">         \n");
      out.write("          <div class=\"row\">\n");
      out.write("            <div class=\"col-md-12 col-sm-12 col-xs-12\">\n");
      out.write("              <div class=\"dashboard_graph\">\n");
      out.write("\n");
      out.write("                <div class=\"row x_title\">\n");
      out.write("                  <div class=\"col-md-6\">\n");
      out.write("                  ");
      out.print( "" );
      out.write("\n");
      out.write("                    <p><strong>Sistema Automatizado Omnilingua</strong> </p>\n");
      out.write("                  </div>                  \n");
      out.write("                </div>\n");
      out.write("\t\t\t\t<!-- \n");
      out.write("\t\t\t\t<img alt=\"\" src=\"../img/inicio_i.png\">-->\n");
      out.write("\t\t\t\t<center>\n");
      out.write("\t\t\t\t<img src=\"../img/SLogo-Omnilingua.png\" alt=\"...\" >\n");
      out.write("\t\t\t\t</center>                \n");
      out.write("                <div class=\"clearfix\"></div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- /page content -->\n");
      out.write("\n");
      out.write("        <!-- footer content -->\n");
      out.write("        <footer>\n");
      out.write("          <div class=\"pull-right\">\n");
      out.write("           <!-- Perfil: < % =Role  % >  &Uacute;ltima Conexi&oacute;n: < % = d t a User[9] % > -->\n");
      out.write("          </div>\n");
      out.write("          <div class=\"clearfix\"></div>\n");
      out.write("        </footer>\n");
      out.write("        <!-- /footer content -->\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- jQuery -->\n");
      out.write("    <script src=\"vendors/jquery/dist/jquery.min.js\"></script>\n");
      out.write("    <!-- Bootstrap -->\n");
      out.write("    <script src=\"vendors/bootstrap/dist/js/bootstrap.min.js\"></script>\n");
      out.write("    <!-- FastClick -->\n");
      out.write("    <script src=\"vendors/fastclick/lib/fastclick.js\"></script>\n");
      out.write("    <!-- NProgress -->\n");
      out.write("    <script src=\"vendors/nprogress/nprogress.js\"></script>\n");
      out.write("    <!-- Chart.js -->\n");
      out.write("<!--     <script src=\"vendors/Chart.js/dist/Chart.min.js\"></script> -->\n");
      out.write("    <!-- gauge.js -->\n");
      out.write("    ");
      out.write("\n");
      out.write("    <!-- bootstrap-progressbar -->\n");
      out.write("    <script src=\"vendors/bootstrap-progressbar/bootstrap-progressbar.min.js\"></script>\n");
      out.write("    <!-- iCheck -->\n");
      out.write("    ");
      out.write("\n");
      out.write("    <!-- Skycons -->\n");
      out.write("    <script src=\"vendors/skycons/skycons.js\"></script>\n");
      out.write("    <!-- Flot -->\n");
      out.write("    ");
      out.write("\n");
      out.write("    <!-- DateJS -->\n");
      out.write("    ");
      out.write("\n");
      out.write("    <!-- JQVMap -->\n");
      out.write("    <script src=\"vendors/jqvmap/dist/jquery.vmap.js\"></script>\n");
      out.write("    <script src=\"vendors/jqvmap/dist/maps/jquery.vmap.world.js\"></script>\n");
      out.write("    <script src=\"vendors/jqvmap/examples/js/jquery.vmap.sampledata.js\"></script>\n");
      out.write("    <!-- bootstrap-daterangepicker -->\n");
      out.write("    ");
      out.write("\n");
      out.write("    <!-- Custom Theme Scripts -->\n");
      out.write("    <script src=\"build/js/custom.min.js\"></script>\n");
      out.write("\n");
      out.write("    <!-- Flot -->\n");
      out.write("    <script>\n");
      out.write("      $(document).ready(function() {\n");
      out.write("        var data1 = [\n");
      out.write("          [gd(2012, 1, 1), 17],\n");
      out.write("          [gd(2012, 1, 2), 74],\n");
      out.write("          [gd(2012, 1, 3), 6],\n");
      out.write("          [gd(2012, 1, 4), 39],\n");
      out.write("          [gd(2012, 1, 5), 20],\n");
      out.write("          [gd(2012, 1, 6), 85],\n");
      out.write("          [gd(2012, 1, 7), 7]\n");
      out.write("        ];\n");
      out.write("\n");
      out.write("        var data2 = [\n");
      out.write("          [gd(2012, 1, 1), 82],\n");
      out.write("          [gd(2012, 1, 2), 23],\n");
      out.write("          [gd(2012, 1, 3), 66],\n");
      out.write("          [gd(2012, 1, 4), 9],\n");
      out.write("          [gd(2012, 1, 5), 119],\n");
      out.write("          [gd(2012, 1, 6), 6],\n");
      out.write("          [gd(2012, 1, 7), 9]\n");
      out.write("        ];\n");
      out.write("        $(\"#canvas_dahs\").length && $.plot($(\"#canvas_dahs\"), [\n");
      out.write("          data1, data2\n");
      out.write("        ], {\n");
      out.write("          series: {\n");
      out.write("            lines: {\n");
      out.write("              show: false,\n");
      out.write("              fill: true\n");
      out.write("            },\n");
      out.write("            splines: {\n");
      out.write("              show: true,\n");
      out.write("              tension: 0.4,\n");
      out.write("              lineWidth: 1,\n");
      out.write("              fill: 0.4\n");
      out.write("            },\n");
      out.write("            points: {\n");
      out.write("              radius: 0,\n");
      out.write("              show: true\n");
      out.write("            },\n");
      out.write("            shadowSize: 2\n");
      out.write("          },\n");
      out.write("          grid: {\n");
      out.write("            verticalLines: true,\n");
      out.write("            hoverable: true,\n");
      out.write("            clickable: true,\n");
      out.write("            tickColor: \"#d5d5d5\",\n");
      out.write("            borderWidth: 1,\n");
      out.write("            color: '#fff'\n");
      out.write("          },\n");
      out.write("          colors: [\"rgba(38, 185, 154, 0.38)\", \"rgba(3, 88, 106, 0.38)\"],\n");
      out.write("          xaxis: {\n");
      out.write("            tickColor: \"rgba(51, 51, 51, 0.06)\",\n");
      out.write("            mode: \"time\",\n");
      out.write("            tickSize: [1, \"day\"],\n");
      out.write("            //tickLength: 10,\n");
      out.write("            axisLabel: \"Date\",\n");
      out.write("            axisLabelUseCanvas: true,\n");
      out.write("            axisLabelFontSizePixels: 12,\n");
      out.write("            axisLabelFontFamily: 'Verdana, Arial',\n");
      out.write("            axisLabelPadding: 10\n");
      out.write("          },\n");
      out.write("          yaxis: {\n");
      out.write("            ticks: 8,\n");
      out.write("            tickColor: \"rgba(51, 51, 51, 0.06)\",\n");
      out.write("          },\n");
      out.write("          tooltip: false\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        function gd(year, month, day) {\n");
      out.write("          return new Date(year, month - 1, day).getTime();\n");
      out.write("        }\n");
      out.write("      });\n");
      out.write("    </script>\n");
      out.write("    <!-- /Flot -->\n");
      out.write("\n");
      out.write("    <!-- JQVMap -->\n");
      out.write("    <script>\n");
      out.write("      $(document).ready(function(){\n");
      out.write("        $('#world-map-gdp').vectorMap({\n");
      out.write("            map: 'world_en',\n");
      out.write("            backgroundColor: null,\n");
      out.write("            color: '#ffffff',\n");
      out.write("            hoverOpacity: 0.7,\n");
      out.write("            selectedColor: '#666666',\n");
      out.write("            enableZoom: true,\n");
      out.write("            showTooltip: true,\n");
      out.write("            values: sample_data,\n");
      out.write("            scaleColors: ['#E6F2F0', '#149B7E'],\n");
      out.write("            normalizeFunction: 'polynomial'\n");
      out.write("        });\n");
      out.write("      });\n");
      out.write("    </script>\n");
      out.write("    <!-- /JQVMap -->\n");
      out.write("\n");
      out.write("    <!-- Skycons -->\n");
      out.write("    <script>\n");
      out.write("      $(document).ready(function() {\n");
      out.write("        var icons = new Skycons({\n");
      out.write("            \"color\": \"#73879C\"\n");
      out.write("          }),\n");
      out.write("          list = [\n");
      out.write("            \"clear-day\", \"clear-night\", \"partly-cloudy-day\",\n");
      out.write("            \"partly-cloudy-night\", \"cloudy\", \"rain\", \"sleet\", \"snow\", \"wind\",\n");
      out.write("            \"fog\"\n");
      out.write("          ],\n");
      out.write("          i;\n");
      out.write("\n");
      out.write("        for (i = list.length; i--;)\n");
      out.write("          icons.set(list[i], list[i]);\n");
      out.write("\n");
      out.write("        icons.play();\n");
      out.write("      });\n");
      out.write("    </script>\n");
      out.write("    <!-- /Skycons -->\n");
      out.write("\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    \n");
      out.write("\n");
      out.write("\n");
      out.write("    \n");
      out.write("    \n");
      out.write("  </body>\n");
      out.write("</html>\n");

//     } else {
//     	response.sendRedirect("login.jsp");
//     }
}catch(Exception _e){
	System.out.println("Error: "+_e);	
	_e.printStackTrace();
	
      out.write("\n");
      out.write("\t<script>window.location='/SAO'</script>    \n");
      out.write("\t");

}

      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
