package mx.com.televisa.derechocorporativo.data.packages;

import mx.com.televisa.derechocorporativo.data.Procedure;

public interface DERCORP_CAPTURA_PKG {

	Procedure DERCORP_TEST_FLASH = new Procedure("DERCORP_TEST_FLASH_PKG.MONITOR_FLASH_PR", 3);
	
	Procedure MONITOR_RESUMEN_GENERAL_PR = new Procedure("DERCORP_TEST_FLASH_PKG.MONITOR_RESUMEN_GENERAL_PR", 21);
	
	Procedure DELETE_CHECKBOX_INFO_PR = new Procedure("DERCORP_CAPTURA_PKG.DELETE_CHECKBOX_INFO_PR", 2);

	Procedure SAVE_INFO_PR = new Procedure("DERCORP_CAPTURA_PKG.SAVE_INFO_PR", 4);

	Procedure UNFORMAT_VAL_CAMPO_NUMERIC_PR = new Procedure("DERCORP_CAPTURA_PKG.UNFORMAT_VAL_CAMPO_NUMERIC_PR", 1);

	Procedure SAVE_MONEDA_PR = new Procedure("DERCORP_CAPTURA_PKG.SAVE_MONEDA_PR", 1);
	
	Procedure SAVE_SEMAFORO_PR = new Procedure("DERCORP_CAPTURA_PKG.SAVE_SEMAFORO_PR", 1);
	
	Procedure CAMBIAR_NOMBRE_CORTO_PR = new Procedure("DERCORP_CAPTURA_PKG.CAMBIAR_NOMBRE_CORTO_PR", 1);
	
	Procedure BORRAR_REG_FLEX_ADM_PR = new Procedure("DERCORP_CAPTURA_PKG.BORRAR_REG_FLEX_ADM_PR", 1);
	
	Procedure BORRAR_PORCENTAJE_PAR_PR = new Procedure("DERCORP_CAPTURA_PKG.BORRAR_PORCENTAJE_PAR_PR", 1);
	
	Procedure DELETE_CHECKBOX_ADM_VIG_PR = new Procedure("DERCORP_CAPTURA_PKG.DELETE_CHECKBOX_ADM_VIG_PR",1);
	
	Procedure DELETE_CHECKBOX_ESCRITURA_PR = new Procedure("DERCORP_CAPTURA_PKG.DELETE_CHECKBOX_ESCRITURA_PR", 1);
	
	Procedure GET_MONEDA_PR = new Procedure("DERCORP_CAPTURA_PKG.GET_MONEDA_PR", 2);

	Procedure RECALCULAR_CAM_CAP_ECS_PR = new Procedure("DERCORP_CAPTURA_PKG.RECALCULAR_CAM_CAP_ECS_PR",2);

	Procedure GET_TEL_COMERCIAL_PR = new Procedure("DERCORP_CAPTURA_PKG.GET_TEL_COMERCIAL_PR", 2);

	Procedure UPDATE_TEL_COMERCIAL_PR = new Procedure("DERCORP_CAPTURA_PKG.UPDATE_TEL_COMERCIAL_PR", 1);

}