package mx.com.televisa.derechocorporativo.model;

// Generated 31-oct-2010 12:16:46 by Hibernate Tools 3.2.4.GA

/**
 * HrSpeciality generated by hbm2java
 */
public class HrSpeciality implements java.io.Serializable {

	private Integer specialityId;
	private HrSpecialityGroup hrSpecialityGroup;
	private String name;

	public HrSpeciality() {
	}

	public HrSpeciality(HrSpecialityGroup hrSpecialityGroup, String name) {
		this.hrSpecialityGroup = hrSpecialityGroup;
		this.name = name;
	}

	public Integer getSpecialityId() {
		return this.specialityId;
	}

	public void setSpecialityId(Integer specialityId) {
		this.specialityId = specialityId;
	}

	public HrSpecialityGroup getHrSpecialityGroup() {
		return this.hrSpecialityGroup;
	}

	public void setHrSpecialityGroup(HrSpecialityGroup hrSpecialityGroup) {
		this.hrSpecialityGroup = hrSpecialityGroup;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
