package mx.com.televisa.derechocorporativo.model;

// Generated 31-oct-2010 12:16:46 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * HrSpecialityGroup generated by hbm2java
 */
public class HrSpecialityGroup implements java.io.Serializable {

	private Integer specialityGroupId;
	private String name;
	private Set<HrSpeciality> hrSpecialities = new HashSet<HrSpeciality>(0);

	public HrSpecialityGroup() {
	}

	public HrSpecialityGroup(String name) {
		this.name = name;
	}

	public HrSpecialityGroup(String name, Set<HrSpeciality> hrSpecialities) {
		this.name = name;
		this.hrSpecialities = hrSpecialities;
	}

	public Integer getSpecialityGroupId() {
		return this.specialityGroupId;
	}

	public void setSpecialityGroupId(Integer specialityGroupId) {
		this.specialityGroupId = specialityGroupId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<HrSpeciality> getHrSpecialities() {
		return this.hrSpecialities;
	}

	public void setHrSpecialities(Set<HrSpeciality> hrSpecialities) {
		this.hrSpecialities = hrSpecialities;
	}

}
