SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER SCHEMA `sysapps`  DEFAULT CHARACTER SET utf8  DEFAULT COLLATE utf8_general_ci ;

CREATE TABLE IF NOT EXISTS `sysapps`.`users` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(10) NOT NULL,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `password` VARCHAR(240) NOT NULL,
  `profile_id` INT(11) NOT NULL,
  `photo` VARCHAR(60) NULL DEFAULT NULL,
  `start_date` DATETIME NULL DEFAULT NULL,
  `end_date` DATETIME NULL DEFAULT NULL,
  `segment1` VARCHAR(60) NULL DEFAULT NULL,
  `segment2` VARCHAR(60) NULL DEFAULT NULL,
  `segment3` VARCHAR(60) NULL DEFAULT NULL,
  `segment4` VARCHAR(60) NULL DEFAULT NULL,
  `segment5` VARCHAR(60) NULL DEFAULT NULL,
  `segment6` VARCHAR(60) NULL DEFAULT NULL,
  `segment7` VARCHAR(60) NULL DEFAULT NULL,
  `segment8` VARCHAR(60) NULL DEFAULT NULL,
  `segment9` VARCHAR(60) NULL DEFAULT NULL,
  `creation_date` DATETIME NOT NULL,
  `last_update_date` DATETIME NULL DEFAULT NULL,
  `created_by` INT(11) NOT NULL,
  `last_update_by` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = MyISAM
AUTO_INCREMENT = 103
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS `sysapps`.`customers` (
  `customer_id` INT(11) NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(100) NULL DEFAULT NULL,
  `last_name` VARCHAR(240) NULL DEFAULT NULL,
  `business_name` VARCHAR(240) NOT NULL,
  `rfc` VARCHAR(20) NOT NULL,
  `address_line1` VARCHAR(240) NULL DEFAULT NULL,
  `address_line2` VARCHAR(240) NULL DEFAULT NULL,
  `address_line3` VARCHAR(45) NULL DEFAULT NULL,
  `city` VARCHAR(45) NULL DEFAULT NULL,
  `state` VARCHAR(45) NULL DEFAULT NULL,
  `country` VARCHAR(45) NULL DEFAULT NULL,
  `postal_code` VARCHAR(10) NULL DEFAULT NULL,
  `segment1` VARCHAR(45) NULL DEFAULT NULL,
  `segment2` VARCHAR(45) NULL DEFAULT NULL,
  `segment3` VARCHAR(45) NULL DEFAULT NULL,
  `segment4` VARCHAR(45) NULL DEFAULT NULL,
  `segment5` VARCHAR(45) NULL DEFAULT NULL,
  `segment6` VARCHAR(45) NULL DEFAULT NULL,
  `segment7` VARCHAR(45) NULL DEFAULT NULL,
  `segment8` VARCHAR(45) NULL DEFAULT NULL,
  `segment9` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(240) NULL DEFAULT NULL,
  `area_code_phone` VARCHAR(4) NULL DEFAULT NULL,
  `phone` VARCHAR(10) NULL DEFAULT NULL,
  `start_date` DATETIME NULL DEFAULT NULL,
  `end_date` DATETIME NULL DEFAULT NULL,
  `born_date` DATETIME NULL DEFAULT NULL,
  `creation_date` DATETIME NOT NULL,
  `last_update_date` DATETIME NULL DEFAULT NULL,
  `created_by` INT(11) NOT NULL,
  `last_update_by` INT(11) NULL DEFAULT NULL,
  `org_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS `sysapps`.`suppliers` (
  `vendor_id` INT(11) NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(100) NULL DEFAULT NULL,
  `last_name` VARCHAR(240) NULL DEFAULT NULL,
  `business_name` VARCHAR(240) NOT NULL,
  `rfc` VARCHAR(20) NOT NULL,
  `address_line1` VARCHAR(240) NULL DEFAULT NULL,
  `address_line2` VARCHAR(240) NULL DEFAULT NULL,
  `address_line3` VARCHAR(45) NULL DEFAULT NULL,
  `city` VARCHAR(45) NULL DEFAULT NULL,
  `state` VARCHAR(45) NULL DEFAULT NULL,
  `country` VARCHAR(45) NULL DEFAULT NULL,
  `postal_code` VARCHAR(10) NULL DEFAULT NULL,
  `segment1` VARCHAR(45) NULL DEFAULT NULL,
  `segment2` VARCHAR(45) NULL DEFAULT NULL,
  `segment3` VARCHAR(45) NULL DEFAULT NULL,
  `segment4` VARCHAR(45) NULL DEFAULT NULL,
  `segment5` VARCHAR(45) NULL DEFAULT NULL,
  `segment6` VARCHAR(45) NULL DEFAULT NULL,
  `segment7` VARCHAR(45) NULL DEFAULT NULL,
  `segment8` VARCHAR(45) NULL DEFAULT NULL,
  `segment9` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(240) NULL DEFAULT NULL,
  `area_code_phone` VARCHAR(4) NULL DEFAULT NULL,
  `phone` VARCHAR(10) NULL DEFAULT NULL,
  `start_date` DATETIME NULL DEFAULT NULL,
  `end_date` DATETIME NULL DEFAULT NULL,
  `born_date` DATETIME NULL DEFAULT NULL,
  `creation_date` DATETIME NOT NULL,
  `last_update_date` DATETIME NULL DEFAULT NULL,
  `created_by` INT(11) NOT NULL,
  `last_update_by` INT(11) NULL DEFAULT NULL,
  `org_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`vendor_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS `sysapps`.`lookups` (
  `lookup_id` INT(11) NOT NULL AUTO_INCREMENT,
  `lookup_code` VARCHAR(50) NOT NULL,
  `lookup_type` VARCHAR(50) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(240) NOT NULL,
  `enabled_flag` VARCHAR(1) NOT NULL,
  `start_date` DATETIME NULL DEFAULT NULL,
  `end_date` DATETIME NULL DEFAULT NULL,
  `segment1` VARCHAR(60) NULL DEFAULT NULL,
  `segment2` VARCHAR(60) NULL DEFAULT NULL,
  `segment3` VARCHAR(60) NULL DEFAULT NULL,
  `segment4` VARCHAR(60) NULL DEFAULT NULL,
  `segment5` VARCHAR(60) NULL DEFAULT NULL,
  `segment6` VARCHAR(60) NULL DEFAULT NULL,
  `segment7` VARCHAR(60) NULL DEFAULT NULL,
  `segment8` VARCHAR(60) NULL DEFAULT NULL,
  `segment9` VARCHAR(60) NULL DEFAULT NULL,
  `creation_date` DATETIME NOT NULL,
  `last_update_date` DATETIME NULL DEFAULT NULL,
  `created_by` INT(11) NOT NULL,
  `last_update_by` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`lookup_id`))
ENGINE = MyISAM
AUTO_INCREMENT = 103
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS `sysapps`.`flex_values` (
  `flex_value_id` INT(11) NOT NULL AUTO_INCREMENT,
  `flex_code` VARCHAR(50) NOT NULL,
  `flex_type` VARCHAR(50) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(240) NOT NULL,
  `enabled_flag` VARCHAR(1) NOT NULL,
  `start_date` DATETIME NULL DEFAULT NULL,
  `end_date` DATETIME NULL DEFAULT NULL,
  `segment1` VARCHAR(60) NULL DEFAULT NULL,
  `segment2` VARCHAR(60) NULL DEFAULT NULL,
  `segment3` VARCHAR(60) NULL DEFAULT NULL,
  `segment4` VARCHAR(60) NULL DEFAULT NULL,
  `segment5` VARCHAR(60) NULL DEFAULT NULL,
  `segment6` VARCHAR(60) NULL DEFAULT NULL,
  `segment7` VARCHAR(60) NULL DEFAULT NULL,
  `segment8` VARCHAR(60) NULL DEFAULT NULL,
  `segment9` VARCHAR(60) NULL DEFAULT NULL,
  `creation_date` DATETIME NOT NULL,
  `last_update_date` DATETIME NULL DEFAULT NULL,
  `created_by` INT(11) NOT NULL,
  `last_update_by` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`flex_value_id`))
ENGINE = MyISAM
AUTO_INCREMENT = 103
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS `sysapps`.`items` (
  `item_id` INT(11) NOT NULL AUTO_INCREMENT,
  `organization_id` INT(11) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(240) NOT NULL,
  `type` VARCHAR(50) NOT NULL,
  `barcode` VARCHAR(100) NOT NULL,
  `enabled_flag` VARCHAR(1) NOT NULL,
  `start_date` DATETIME NULL DEFAULT NULL,
  `end_date` DATETIME NULL DEFAULT NULL,
  `segment_context` VARCHAR(60) NULL DEFAULT NULL,
  `segment1` VARCHAR(60) NULL DEFAULT NULL,
  `segment2` VARCHAR(60) NULL DEFAULT NULL,
  `segment3` VARCHAR(60) NULL DEFAULT NULL,
  `segment4` VARCHAR(60) NULL DEFAULT NULL,
  `segment5` VARCHAR(60) NULL DEFAULT NULL,
  `segment6` VARCHAR(60) NULL DEFAULT NULL,
  `segment7` VARCHAR(60) NULL DEFAULT NULL,
  `segment8` VARCHAR(60) NULL DEFAULT NULL,
  `segment9` VARCHAR(60) NULL DEFAULT NULL,
  `creation_date` DATETIME NOT NULL,
  `last_update_date` DATETIME NULL DEFAULT NULL,
  `created_by` INT(11) NOT NULL,
  `last_update_by` INT(11) NULL DEFAULT NULL,
  `org_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`item_id`))
ENGINE = MyISAM
AUTO_INCREMENT = 103
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


DELIMITER $$
USE `sysapps`$$
CREATE PROCEDURE `routine1` ()
BEGIN

END$$

DELIMITER ;

DELIMITER $$
USE `sysapps`$$
CREATE PROCEDURE `routine2` ()
BEGIN

END$$

DELIMITER ;

DELIMITER $$
USE `sysapps`$$
CREATE PROCEDURE `routine3` ()
BEGIN

END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
